/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './submenu.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './submenu.component.css.shim';
export class Wrapper_SubmenuComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SubmenuComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.SubmenuComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const nodeDebugInfos_SubmenuComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.SubmenuComponent],import0.SubmenuComponent,{})];
var renderType_SubmenuComponent_Host:import3.RenderComponentType = import4.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_SubmenuComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.SubmenuComponent>;
  _SubmenuComponent_0_3:Wrapper_SubmenuComponent;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SubmenuComponent_Host0,renderType_SubmenuComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SubmenuComponent_Host0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'submenu',import4.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_SubmenuComponent0(this.viewUtils,this,0,this._el_0);
    this._SubmenuComponent_0_3 = new Wrapper_SubmenuComponent();
    this.compView_0.create(this._SubmenuComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._SubmenuComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SubmenuComponent) && (0 === requestNodeIndex))) { return this._SubmenuComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._SubmenuComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SubmenuComponentNgFactory:import8.ComponentFactory<import0.SubmenuComponent> = new import8.ComponentFactory<import0.SubmenuComponent>('submenu',View_SubmenuComponent_Host0,import0.SubmenuComponent);
const styles_SubmenuComponent:any[] = [import9.styles];
const nodeDebugInfos_SubmenuComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_SubmenuComponent:import3.RenderComponentType = import4.createRenderComponentType('/home/peter/Desktop/git/angular2-aot-webpack/src/app/common/submenu/submenu.component.html',0,import5.ViewEncapsulation.Emulated,styles_SubmenuComponent,{});
export class View_SubmenuComponent0 extends import1.DebugAppView<import0.SubmenuComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SubmenuComponent0,renderType_SubmenuComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SubmenuComponent0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',this.debug(1,0,23));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','row'),this.debug(2,1,4));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',this.debug(3,1,21));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','col-md-12'),this.debug(4,2,8));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',this.debug(5,2,31));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'a',new import4.InlineArray2(2,'href','#'),this.debug(6,3,12));
    this._text_7 = this.renderer.createText(this._el_6,'Overview',this.debug(7,3,24));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',this.debug(8,3,36));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_4,'a',new import4.InlineArray2(2,'href','#'),this.debug(9,4,12));
    this._text_10 = this.renderer.createText(this._el_9,'Download',this.debug(10,4,24));
    this._text_11 = this.renderer.createText(this._el_4,'\n            ',this.debug(11,4,36));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_4,'a',new import4.InlineArray2(2,'href','#'),this.debug(12,5,12));
    this._text_13 = this.renderer.createText(this._el_12,'Technical',this.debug(13,5,24));
    this._text_14 = this.renderer.createText(this._el_4,'\n        ',this.debug(14,5,37));
    this._text_15 = this.renderer.createText(this._el_2,'\n    ',this.debug(15,6,14));
    this._text_16 = this.renderer.createText(this._el_0,'\n',this.debug(16,7,10));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16
    ]
    ),(null as any));
    return (null as any);
  }
}