/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['html[_ngcontent-%COMP%], body[_ngcontent-%COMP%]{src:url("https://fonts.googleapis.com/css?family=Libre+Franklin:100,300,400,500");font-family:\'Libre Franklin\', sans-serif;height:100%;overflow:auto}h1[_ngcontent-%COMP%], h2[_ngcontent-%COMP%], h3[_ngcontent-%COMP%], h4[_ngcontent-%COMP%]{font-weight:300}p[_ngcontent-%COMP%]{font-weight:200}p.lead[_ngcontent-%COMP%]{font-weight:100}.table[_ngcontent-%COMP%]   thead[_ngcontent-%COMP%]   th[_ngcontent-%COMP%]{font-weight:400}.table[_ngcontent-%COMP%]   td[_ngcontent-%COMP%]{font-weight:300}@font-face{font-family:slamby-logo}.main[_ngcontent-%COMP%]{background:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.5)),url(./images/team.jpg) 0 0 no-repeat;background-size:cover;margin-top:-50px;padding-top:400px;padding-bottom:50px}.main[_ngcontent-%COMP%]   .message[_ngcontent-%COMP%]{position:relative;min-height:1px;padding-left:15px;padding-right:15px;position:relative;float:left;width:100%;min-height:1px;padding-left:15px;padding-right:15px;color:white;background-color:rgba(0,0,0,0.4)}@media (min-width: 992px){.main[_ngcontent-%COMP%]   .message[_ngcontent-%COMP%]{float:left;width:50%}}'];