/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['html[_ngcontent-%COMP%], body[_ngcontent-%COMP%]{src:url("https://fonts.googleapis.com/css?family=Libre+Franklin:100,300,400,500");font-family:\'Libre Franklin\', sans-serif;height:100%;overflow:auto}h1[_ngcontent-%COMP%], h2[_ngcontent-%COMP%], h3[_ngcontent-%COMP%], h4[_ngcontent-%COMP%]{font-weight:300}p[_ngcontent-%COMP%]{font-weight:200}p.lead[_ngcontent-%COMP%]{font-weight:100}.table[_ngcontent-%COMP%]   thead[_ngcontent-%COMP%]   th[_ngcontent-%COMP%]{font-weight:400}.table[_ngcontent-%COMP%]   td[_ngcontent-%COMP%]{font-weight:300}@font-face{font-family:slamby-logo}.notFoundModule[_ngcontent-%COMP%]{text-align:center}.notFoundModule[_ngcontent-%COMP%]   .box[_ngcontent-%COMP%]{margin-top:50px}.notFoundModule[_ngcontent-%COMP%]   .box[_ngcontent-%COMP%]   .icon[_ngcontent-%COMP%]   i[_ngcontent-%COMP%]{font-size:70px;font-weight:100}'];