/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './commercial-license-oem.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './legal.component.css.shim';
import * as import10 from '../common/header/header.component';
import * as import11 from './legal-menu.component';
import * as import12 from '../common/header/header.component.ngfactory';
import * as import13 from './legal-menu.component.ngfactory';
export class Wrapper_CommercialLicenseOemComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CommercialLicenseOemComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.CommercialLicenseOemComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const nodeDebugInfos_CommercialLicenseOemComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.CommercialLicenseOemComponent],import0.CommercialLicenseOemComponent,{})];
var renderType_CommercialLicenseOemComponent_Host:import3.RenderComponentType = import4.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_CommercialLicenseOemComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.CommercialLicenseOemComponent>;
  _CommercialLicenseOemComponent_0_3:Wrapper_CommercialLicenseOemComponent;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CommercialLicenseOemComponent_Host0,renderType_CommercialLicenseOemComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_CommercialLicenseOemComponent_Host0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ng-component',import4.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_CommercialLicenseOemComponent0(this.viewUtils,this,0,this._el_0);
    this._CommercialLicenseOemComponent_0_3 = new Wrapper_CommercialLicenseOemComponent();
    this.compView_0.create(this._CommercialLicenseOemComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._CommercialLicenseOemComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CommercialLicenseOemComponent) && (0 === requestNodeIndex))) { return this._CommercialLicenseOemComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._CommercialLicenseOemComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CommercialLicenseOemComponentNgFactory:import8.ComponentFactory<import0.CommercialLicenseOemComponent> = new import8.ComponentFactory<import0.CommercialLicenseOemComponent>('ng-component',View_CommercialLicenseOemComponent_Host0,import0.CommercialLicenseOemComponent);
const styles_CommercialLicenseOemComponent:any[] = [import9.styles];
const nodeDebugInfos_CommercialLicenseOemComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo([import10.HeaderComponent],import10.HeaderComponent,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import11.LegalMenuComponent],import11.LegalMenuComponent,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_CommercialLicenseOemComponent:import3.RenderComponentType = import4.createRenderComponentType('/home/peter/Desktop/git/angular2-aot-webpack/src/app/legal/commercial-license-oem.component.html',0,import5.ViewEncapsulation.Emulated,styles_CommercialLicenseOemComponent,{});
export class View_CommercialLicenseOemComponent0 extends import1.DebugAppView<import0.CommercialLicenseOemComponent> {
  _el_0:any;
  compView_0:import1.AppView<import10.HeaderComponent>;
  _HeaderComponent_0_3:import12.Wrapper_HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import11.LegalMenuComponent>;
  _LegalMenuComponent_4_3:import13.Wrapper_LegalMenuComponent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CommercialLicenseOemComponent0,renderType_CommercialLicenseOemComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_CommercialLicenseOemComponent0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'pm-header',import4.EMPTY_INLINE_ARRAY,this.debug(0,0,0));
    this.compView_0 = new import12.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import12.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(1,0,23));
    this._el_2 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),this.debug(2,2,0));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,2,23));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'legalMenu',import4.EMPTY_INLINE_ARRAY,this.debug(4,3,4));
    this.compView_4 = new import13.View_LegalMenuComponent0(this.viewUtils,this,4,this._el_4);
    this._LegalMenuComponent_4_3 = new import13.Wrapper_LegalMenuComponent();
    this.compView_4.create(this._LegalMenuComponent_4_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',this.debug(5,3,27));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','body'),this.debug(6,4,4));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',this.debug(7,4,22));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_6,'h1',import4.EMPTY_INLINE_ARRAY,this.debug(8,5,8));
    this._text_9 = this.renderer.createText(this._el_8,'Extension to the slamby api commercial license for royalty free distribution (oem)',this.debug(9,5,12));
    this._text_10 = this.renderer.createText(this._el_6,'\n        ',this.debug(10,5,99));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_6,'h2',import4.EMPTY_INLINE_ARRAY,this.debug(11,6,8));
    this._text_12 = this.renderer.createText(this._el_11,'1. Definitions',this.debug(12,6,12));
    this._text_13 = this.renderer.createText(this._el_6,'\n        ',this.debug(13,6,31));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(14,7,8));
    this._text_15 = this.renderer.createText(this._el_14,'When used in this Agreement, the following terms shall have the respective meanings indicated, such meanings to be applicable to both the singular and plural forms of the terms defined:',this.debug(15,7,11));
    this._text_16 = this.renderer.createText(this._el_6,'\n        ',this.debug(16,7,200));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_6,'ul',import4.EMPTY_INLINE_ARRAY,this.debug(17,8,8));
    this._text_18 = this.renderer.createText(this._el_17,'\n            ',this.debug(18,8,12));
    this._el_19 = import4.createRenderElement(this.renderer,this._el_17,'li',import4.EMPTY_INLINE_ARRAY,this.debug(19,9,12));
    this._text_20 = this.renderer.createText(this._el_19,'“We” or “Us” or “Slamby” or “Our” or the “Company” refers to Slamby-Semantics Ltd.',this.debug(20,9,16));
    this._text_21 = this.renderer.createText(this._el_17,'\n            ',this.debug(21,9,103));
    this._el_22 = import4.createRenderElement(this.renderer,this._el_17,'li',import4.EMPTY_INLINE_ARRAY,this.debug(22,10,12));
    this._text_23 = this.renderer.createText(this._el_22,'“You” and “Your” and “User” refers to the entity and/or individual person, natural or legal, consenting to, and entering into, this Agreement.',this.debug(23,10,16));
    this._text_24 = this.renderer.createText(this._el_17,'\n            ',this.debug(24,10,163));
    this._el_25 = import4.createRenderElement(this.renderer,this._el_17,'li',import4.EMPTY_INLINE_ARRAY,this.debug(25,11,12));
    this._text_26 = this.renderer.createText(this._el_25,'"Licensor" means Slamby.',this.debug(26,11,16));
    this._text_27 = this.renderer.createText(this._el_17,'\n            ',this.debug(27,11,45));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_17,'li',import4.EMPTY_INLINE_ARRAY,this.debug(28,12,12));
    this._text_29 = this.renderer.createText(this._el_28,'"Software" means (a) all of the contents of the files, disk(s), disk image(s), Docker containers or other media with which this Agreement is provided, including but not limited to ((i) digital images (ii) related explanatory written materials or files ("Documentation"); and (iii) fonts; and (b) upgrades, modified versions, updates, additions, and copies of the Software, if any, licensed to you by Slamby (collectively, "Updates").',this.debug(29,12,16));
    this._text_30 = this.renderer.createText(this._el_17,'\n            ',this.debug(30,12,454));
    this._el_31 = import4.createRenderElement(this.renderer,this._el_17,'li',import4.EMPTY_INLINE_ARRAY,this.debug(31,13,12));
    this._text_32 = this.renderer.createText(this._el_31,'"Use" or "Using" means to access, install, download, copy or otherwise benefit from using the functionality of the Software.',this.debug(32,13,16));
    this._text_33 = this.renderer.createText(this._el_17,'\n            ',this.debug(33,13,145));
    this._el_34 = import4.createRenderElement(this.renderer,this._el_17,'li',import4.EMPTY_INLINE_ARRAY,this.debug(34,14,12));
    this._text_35 = this.renderer.createText(this._el_34,'"Licensee" means You or Your Company, unless otherwise indicated.',this.debug(35,14,16));
    this._text_36 = this.renderer.createText(this._el_17,'\n            ',this.debug(36,14,86));
    this._el_37 = import4.createRenderElement(this.renderer,this._el_17,'li',import4.EMPTY_INLINE_ARRAY,this.debug(37,15,12));
    this._text_38 = this.renderer.createText(this._el_37,'"System" means Windows OS, GNU/Linux or Mac OS X, Docker or any virtual machine.',this.debug(38,15,16));
    this._text_39 = this.renderer.createText(this._el_17,'\n        ',this.debug(39,15,101));
    this._text_40 = this.renderer.createText(this._el_6,'\n        ',this.debug(40,16,13));
    this._el_41 = import4.createRenderElement(this.renderer,this._el_6,'h2',import4.EMPTY_INLINE_ARRAY,this.debug(41,17,8));
    this._text_42 = this.renderer.createText(this._el_41,'2. General Use',this.debug(42,17,12));
    this._text_43 = this.renderer.createText(this._el_6,'\n        ',this.debug(43,17,31));
    this._el_44 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(44,18,8));
    this._text_45 = this.renderer.createText(this._el_44,'As long as the Licensee complies with the terms of this extension of End User License Agreement (the "Agreement") and the Agreement itself, the Licensor grants the Licensee a non-exclusive right to install and Use the Software for the purposes described in the Documentation under the following conditions:',this.debug(45,18,11));
    this._text_46 = this.renderer.createText(this._el_6,'\n        ',this.debug(46,18,321));
    this._el_47 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(47,19,8));
    this._text_48 = this.renderer.createText(this._el_47,'The Software may be installed and used by the Licensee for business, commercial and money-earning purposes.',this.debug(48,19,11));
    this._text_49 = this.renderer.createText(this._el_6,'\n        ',this.debug(49,19,122));
    this._el_50 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(50,20,8));
    this._text_51 = this.renderer.createText(this._el_50,'This License can be deployed on any number of systems.',this.debug(51,20,11));
    this._text_52 = this.renderer.createText(this._el_6,'\n        ',this.debug(52,20,69));
    this._el_53 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(53,21,8));
    this._text_54 = this.renderer.createText(this._el_53,'The Software under this License may be incorporated into software/hardware projects sold by the Licensee.',this.debug(54,21,11));
    this._text_55 = this.renderer.createText(this._el_6,'\n        ',this.debug(55,21,120));
    this._el_56 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(56,22,8));
    this._text_57 = this.renderer.createText(this._el_56,'The Licensee may physically or electronically distribute the Software to his manufacturing and service partners but only as an intermediary product, requiring incorporation of the Software into the software or hardware developed by the Licensee in cases when the manufacturing process involves the Licensee\'s partner\'s job to complete the project before distributing it to end-users.',this.debug(57,22,11));
    this._text_58 = this.renderer.createText(this._el_6,'\n        ',this.debug(58,22,398));
    this._el_59 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(59,23,8));
    this._text_60 = this.renderer.createText(this._el_59,'The Licensee or his manufacturing and service partners may reproduce and physically or electronically distribute the Software only as an integral part of or incorporated into their software or hardware product.',this.debug(60,23,11));
    this._text_61 = this.renderer.createText(this._el_6,'\n        ',this.debug(61,23,225));
    this._el_62 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(62,24,8));
    this._text_63 = this.renderer.createText(this._el_62,'This License entitles the Licensee to the unlimited redistribution of the Licensor\'s technology as a part of the Licensee\'s product.',this.debug(63,24,11));
    this._text_64 = this.renderer.createText(this._el_6,'\n        ',this.debug(64,24,147));
    this._el_65 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(65,25,8));
    this._text_66 = this.renderer.createText(this._el_65,'This License is royalty-free, i.e. the Licensee does not need to pay a fee per every order of his product with the incorporated Licensor\'s technology.',this.debug(66,25,11));
    this._text_67 = this.renderer.createText(this._el_6,'\n        ',this.debug(67,25,165));
    this._el_68 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(68,26,8));
    this._text_69 = this.renderer.createText(this._el_68,'This License cannot be used by the Licensee to develop a software application that would compete with products marketed by the Licensor.',this.debug(69,26,11));
    this._text_70 = this.renderer.createText(this._el_6,'\n        ',this.debug(70,26,151));
    this._el_71 = import4.createRenderElement(this.renderer,this._el_6,'h2',import4.EMPTY_INLINE_ARRAY,this.debug(71,27,8));
    this._text_72 = this.renderer.createText(this._el_71,'3. Intellectual Property Rights',this.debug(72,27,12));
    this._text_73 = this.renderer.createText(this._el_6,'\n        ',this.debug(73,27,48));
    this._el_74 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(74,28,8));
    this._text_75 = this.renderer.createText(this._el_74,'3.1 This License does not transmit any intellectual rights on the Software. The Software and any copies that the Licensee is authorized by the Licensor to make are the intellectual property of and are owned by the Licensor.',this.debug(75,28,11));
    this._text_76 = this.renderer.createText(this._el_6,'\n        ',this.debug(76,28,238));
    this._el_77 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(77,29,8));
    this._text_78 = this.renderer.createText(this._el_77,'3.2 The Software is protected by copyright, including without limitation by Copyright Law and international treaty provisions.',this.debug(78,29,11));
    this._text_79 = this.renderer.createText(this._el_6,'\n        ',this.debug(79,29,141));
    this._el_80 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(80,30,8));
    this._text_81 = this.renderer.createText(this._el_80,'3.3 Any copies that the Licensee is permitted to make pursuant to this Agreement must contain the same copyright and other proprietary notices that appear on or in the Software.',this.debug(81,30,11));
    this._text_82 = this.renderer.createText(this._el_6,'\n        ',this.debug(82,30,192));
    this._el_83 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(83,31,8));
    this._text_84 = this.renderer.createText(this._el_83,'3.4 Any information supplied by the Licensor or obtained by the Licensee, as permitted hereunder, may only be used by the Licensee for the purpose described herein and may not be disclosed to any third party or used to create any software which is substantially similar to the expression of the Software.',this.debug(84,31,11));
    this._text_85 = this.renderer.createText(this._el_6,'\n        ',this.debug(85,31,319));
    this._el_86 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(86,32,8));
    this._text_87 = this.renderer.createText(this._el_86,'3.5 Trademarks shall be used in accordance with accepted trademark practice, including identification of trademarks owners\' names. Trademarks can only be used to identify printed output produced by the Software and such use of any trademark does not give the Licensee any rights of ownership in that trademark.',this.debug(87,32,11));
    this._text_88 = this.renderer.createText(this._el_6,'\n        ',this.debug(88,32,325));
    this._el_89 = import4.createRenderElement(this.renderer,this._el_6,'h2',import4.EMPTY_INLINE_ARRAY,this.debug(89,33,8));
    this._text_90 = this.renderer.createText(this._el_89,'License Transfer',this.debug(90,33,12));
    this._text_91 = this.renderer.createText(this._el_6,'\n        ',this.debug(91,33,33));
    this._el_92 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(92,34,8));
    this._text_93 = this.renderer.createText(this._el_92,'4.1 This License is non-transferable. The Licensee may not transfer the rights to Use the Software to third parties (another person or legal entity).',this.debug(93,34,11));
    this._text_94 = this.renderer.createText(this._el_6,'\n        ',this.debug(94,34,164));
    this._el_95 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(95,35,8));
    this._text_96 = this.renderer.createText(this._el_95,'4.2 The Licensee may not rent, lease, sub-license, lend or transfer any versions or copies of the Software to third parties (another person or legal entity).',this.debug(96,35,11));
    this._text_97 = this.renderer.createText(this._el_6,'\n        ',this.debug(97,35,172));
    this._el_98 = import4.createRenderElement(this.renderer,this._el_6,'p',import4.EMPTY_INLINE_ARRAY,this.debug(98,36,8));
    this._text_99 = this.renderer.createText(this._el_98,'4.3 The Licensee may make a back-up copy of the Software, provided a backup copy is not installed or used on any system not belonging to the Licensee. The Licensee may not transfer the rights to install or use a backup copy of the Software to third parties (another person or legal entity).',this.debug(99,36,11));
    this._text_100 = this.renderer.createText(this._el_6,'\n    ',this.debug(100,36,305));
    this._text_101 = this.renderer.createText(this._el_2,'\n',this.debug(101,37,10));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._text_101
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    if (((token === import11.LegalMenuComponent) && (4 === requestNodeIndex))) { return this._LegalMenuComponent_4_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(4,3,4);
    this._LegalMenuComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    this.compView_4.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_4.destroy();
    this.debug(0,0,0);
  }
}