/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './getting-started.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './getting-started.component.css.shim';
import * as import10 from '../common/header/header.component';
import * as import11 from '../common/header/header.component.ngfactory';
export class Wrapper_GettingStartedComponent {
  /*private*/ _eventHandler:Function;
  context:import0.GettingStartedComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.GettingStartedComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const nodeDebugInfos_GettingStartedComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.GettingStartedComponent],import0.GettingStartedComponent,{})];
var renderType_GettingStartedComponent_Host:import3.RenderComponentType = import4.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_GettingStartedComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.GettingStartedComponent>;
  _GettingStartedComponent_0_3:Wrapper_GettingStartedComponent;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_GettingStartedComponent_Host0,renderType_GettingStartedComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_GettingStartedComponent_Host0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ng-component',import4.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_GettingStartedComponent0(this.viewUtils,this,0,this._el_0);
    this._GettingStartedComponent_0_3 = new Wrapper_GettingStartedComponent();
    this.compView_0.create(this._GettingStartedComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._GettingStartedComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.GettingStartedComponent) && (0 === requestNodeIndex))) { return this._GettingStartedComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._GettingStartedComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const GettingStartedComponentNgFactory:import8.ComponentFactory<import0.GettingStartedComponent> = new import8.ComponentFactory<import0.GettingStartedComponent>('ng-component',View_GettingStartedComponent_Host0,import0.GettingStartedComponent);
const styles_GettingStartedComponent:any[] = [import9.styles];
const nodeDebugInfos_GettingStartedComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo([import10.HeaderComponent],import10.HeaderComponent,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_GettingStartedComponent:import3.RenderComponentType = import4.createRenderComponentType('/home/peter/Desktop/git/angular2-aot-webpack/src/app/getting-started/getting-started.component.html',0,import5.ViewEncapsulation.Emulated,styles_GettingStartedComponent,{});
export class View_GettingStartedComponent0 extends import1.DebugAppView<import0.GettingStartedComponent> {
  _el_0:any;
  compView_0:import1.AppView<import10.HeaderComponent>;
  _HeaderComponent_0_3:import11.Wrapper_HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  _el_104:any;
  _el_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _text_109:any;
  _el_110:any;
  _text_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _text_115:any;
  _el_116:any;
  _text_117:any;
  _el_118:any;
  _text_119:any;
  _text_120:any;
  _el_121:any;
  _text_122:any;
  _el_123:any;
  _text_124:any;
  _text_125:any;
  _el_126:any;
  _el_127:any;
  _text_128:any;
  _el_129:any;
  _text_130:any;
  _text_131:any;
  _el_132:any;
  _text_133:any;
  _text_134:any;
  _el_135:any;
  _text_136:any;
  _text_137:any;
  _el_138:any;
  _el_139:any;
  _text_140:any;
  _text_141:any;
  _text_142:any;
  _el_143:any;
  _text_144:any;
  _el_145:any;
  _text_146:any;
  _text_147:any;
  _el_148:any;
  _text_149:any;
  _text_150:any;
  _el_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _text_155:any;
  _el_156:any;
  _text_157:any;
  _el_158:any;
  _text_159:any;
  _el_160:any;
  _text_161:any;
  _text_162:any;
  _el_163:any;
  _text_164:any;
  _el_165:any;
  _text_166:any;
  _el_167:any;
  _text_168:any;
  _el_169:any;
  _text_170:any;
  _text_171:any;
  _el_172:any;
  _text_173:any;
  _text_174:any;
  _text_175:any;
  _text_176:any;
  _el_177:any;
  _text_178:any;
  _el_179:any;
  _text_180:any;
  _el_181:any;
  _text_182:any;
  _text_183:any;
  _el_184:any;
  _el_185:any;
  _text_186:any;
  _text_187:any;
  _text_188:any;
  _el_189:any;
  _text_190:any;
  _el_191:any;
  _text_192:any;
  _text_193:any;
  _el_194:any;
  _el_195:any;
  _text_196:any;
  _text_197:any;
  _text_198:any;
  _el_199:any;
  _text_200:any;
  _el_201:any;
  _text_202:any;
  _text_203:any;
  _el_204:any;
  _el_205:any;
  _text_206:any;
  _text_207:any;
  _text_208:any;
  _el_209:any;
  _text_210:any;
  _el_211:any;
  _text_212:any;
  _text_213:any;
  _el_214:any;
  _el_215:any;
  _text_216:any;
  _text_217:any;
  _text_218:any;
  _el_219:any;
  _text_220:any;
  _el_221:any;
  _text_222:any;
  _text_223:any;
  _el_224:any;
  _el_225:any;
  _text_226:any;
  _text_227:any;
  _text_228:any;
  _text_229:any;
  _text_230:any;
  _el_231:any;
  _text_232:any;
  _text_233:any;
  _el_234:any;
  _text_235:any;
  _el_236:any;
  _text_237:any;
  _text_238:any;
  _el_239:any;
  _text_240:any;
  _el_241:any;
  _text_242:any;
  _text_243:any;
  _el_244:any;
  _text_245:any;
  _text_246:any;
  _el_247:any;
  _text_248:any;
  _el_249:any;
  _text_250:any;
  _text_251:any;
  _el_252:any;
  _text_253:any;
  _text_254:any;
  _el_255:any;
  _text_256:any;
  _text_257:any;
  _el_258:any;
  _text_259:any;
  _el_260:any;
  _text_261:any;
  _text_262:any;
  _el_263:any;
  _text_264:any;
  _el_265:any;
  _text_266:any;
  _text_267:any;
  _text_268:any;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_GettingStartedComponent0,renderType_GettingStartedComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_GettingStartedComponent0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'pm-header',import4.EMPTY_INLINE_ARRAY,this.debug(0,0,0));
    this.compView_0 = new import11.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import11.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',this.debug(1,0,23));
    this._el_2 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),this.debug(2,1,0));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,1,23));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','menu'),this.debug(4,2,4));
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',this.debug(5,2,22));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'div',new import4.InlineArray2(2,'class','list-group'),this.debug(6,3,8));
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',this.debug(7,3,32));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_6,'a',new import4.InlineArray8(6,'class','list-group-item','href','#api-install','pageScroll',''),this.debug(8,4,12));
    this._text_9 = this.renderer.createText(this._el_8,'API install',this.debug(9,4,70));
    this._text_10 = this.renderer.createText(this._el_6,'\n            ',this.debug(10,4,85));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_6,'a',new import4.InlineArray8(6,'class','list-group-item','href','#api-activation','pageScroll',''),this.debug(11,5,12));
    this._text_12 = this.renderer.createText(this._el_11,'API activation',this.debug(12,5,73));
    this._text_13 = this.renderer.createText(this._el_6,'\n            ',this.debug(13,5,91));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_6,'a',new import4.InlineArray8(6,'class','list-group-item','href','#slamby-insight','pageScroll',''),this.debug(14,6,12));
    this._text_15 = this.renderer.createText(this._el_14,'Slamby Insight',this.debug(15,6,73));
    this._text_16 = this.renderer.createText(this._el_6,'\n            ',this.debug(16,6,91));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_6,'a',new import4.InlineArray8(6,'class','list-group-item','href','#integration','pageScroll',''),this.debug(17,7,12));
    this._text_18 = this.renderer.createText(this._el_17,'Integration',this.debug(18,7,70));
    this._text_19 = this.renderer.createText(this._el_6,'\n            ',this.debug(19,7,85));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_6,'a',new import4.InlineArray8(6,'class','list-group-item','href','#documentation','pageScroll',''),this.debug(20,8,12));
    this._text_21 = this.renderer.createText(this._el_20,'Documentation',this.debug(21,8,72));
    this._text_22 = this.renderer.createText(this._el_6,'\n            ',this.debug(22,8,89));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_6,'a',new import4.InlineArray8(6,'class','list-group-item','href','#support','pageScroll',''),this.debug(23,9,12));
    this._text_24 = this.renderer.createText(this._el_23,'Support',this.debug(24,9,66));
    this._text_25 = this.renderer.createText(this._el_6,'\n        ',this.debug(25,9,77));
    this._text_26 = this.renderer.createText(this._el_4,'\n    ',this.debug(26,10,14));
    this._text_27 = this.renderer.createText(this._el_2,'\n    ',this.debug(27,11,10));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','body'),this.debug(28,12,4));
    this._text_29 = this.renderer.createText(this._el_28,'\n        ',this.debug(29,12,22));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_28,'h1',import4.EMPTY_INLINE_ARRAY,this.debug(30,13,8));
    this._text_31 = this.renderer.createText(this._el_30,'Getting started',this.debug(31,13,12));
    this._text_32 = this.renderer.createText(this._el_28,'\n        ',this.debug(32,13,32));
    this._el_33 = import4.createRenderElement(this.renderer,this._el_28,'p',new import4.InlineArray2(2,'class','lead'),this.debug(33,14,8));
    this._text_34 = this.renderer.createText(this._el_33,'Welcome to Slamby. Congratulation, you made the very first step to work with our awesome products. You are almost done, but before getting started working with your Slamby product, here are a few useful information.',this.debug(34,14,24));
    this._text_35 = this.renderer.createText(this._el_28,'\n\n        ',this.debug(35,14,243));
    this._el_36 = import4.createRenderElement(this.renderer,this._el_28,'h2',new import4.InlineArray2(2,'id','api-install'),this.debug(36,16,8));
    this._text_37 = this.renderer.createText(this._el_36,'API install',this.debug(37,16,29));
    this._text_38 = this.renderer.createText(this._el_28,'\n        ',this.debug(38,16,45));
    this._el_39 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(39,17,8));
    this._text_40 = this.renderer.createText(this._el_39,'You can use your Slamby API as a SaaS, or you can download, and host is by yourself. When you want to host it by yourself, the first thing you need to manage is the installation. To install Slamby API, please check the product readme and the installation guide.',this.debug(40,17,11));
    this._text_41 = this.renderer.createText(this._el_28,'\n        ',this.debug(41,17,276));
    this._el_42 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(42,18,8));
    this._text_43 = this.renderer.createText(this._el_42,'Product documentation: ',this.debug(43,18,11));
    this._el_44 = import4.createRenderElement(this.renderer,this._el_42,'a',new import4.InlineArray4(4,'href','https://github.com/slamby/slamby-api','target','_blank'),this.debug(44,18,34));
    this._text_45 = this.renderer.createText(this._el_44,'https://github.com/slamby/slamby-api',this.debug(45,18,97));
    this._text_46 = this.renderer.createText(this._el_28,'\n        ',this.debug(46,18,141));
    this._el_47 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(47,19,8));
    this._text_48 = this.renderer.createText(this._el_47,'Using Docker Compose, here are the installation steps:',this.debug(48,19,11));
    this._text_49 = this.renderer.createText(this._el_28,'\n        ',this.debug(49,19,69));
    this._el_50 = import4.createRenderElement(this.renderer,this._el_28,'ol',import4.EMPTY_INLINE_ARRAY,this.debug(50,20,8));
    this._text_51 = this.renderer.createText(this._el_50,'\n            ',this.debug(51,20,12));
    this._el_52 = import4.createRenderElement(this.renderer,this._el_50,'li',import4.EMPTY_INLINE_ARRAY,this.debug(52,21,12));
    this._text_53 = this.renderer.createText(this._el_52,'Install Docker on your machine: ',this.debug(53,21,16));
    this._el_54 = import4.createRenderElement(this.renderer,this._el_52,'a',new import4.InlineArray4(4,'href','https://docs.docker.com/engine/installation','target',''),this.debug(54,21,48));
    this._text_55 = this.renderer.createText(this._el_54,'Official Docker installation guide',this.debug(55,21,112));
    this._text_56 = this.renderer.createText(this._el_50,'\n            ',this.debug(56,21,155));
    this._el_57 = import4.createRenderElement(this.renderer,this._el_50,'li',import4.EMPTY_INLINE_ARRAY,this.debug(57,22,12));
    this._text_58 = this.renderer.createText(this._el_57,'Install Docker Compose on your machine (minimum 1.9.0 required): ',this.debug(58,22,16));
    this._el_59 = import4.createRenderElement(this.renderer,this._el_57,'a',new import4.InlineArray4(4,'href','https://docs.docker.com/compose/install','target','_blank'),this.debug(59,22,81));
    this._text_60 = this.renderer.createText(this._el_59,'Official Docker Compose installation guide',this.debug(60,22,147));
    this._text_61 = this.renderer.createText(this._el_50,'\n            ',this.debug(61,22,198));
    this._el_62 = import4.createRenderElement(this.renderer,this._el_50,'li',import4.EMPTY_INLINE_ARRAY,this.debug(62,23,12));
    this._text_63 = this.renderer.createText(this._el_62,'Download our Docker Compose file',this.debug(63,23,16));
    this._el_64 = import4.createRenderElement(this.renderer,this._el_62,'br',import4.EMPTY_INLINE_ARRAY,this.debug(64,23,48));
    this._el_65 = import4.createRenderElement(this.renderer,this._el_62,'code',import4.EMPTY_INLINE_ARRAY,this.debug(65,23,52));
    this._text_66 = this.renderer.createText(this._el_65,'$ curl -L "https://github.com/slamby/slamby-api/releases/download/v1.2.0/docker-compose.yml" > docker-compose.yml',this.debug(66,23,58));
    this._text_67 = this.renderer.createText(this._el_50,'\n            ',this.debug(67,23,183));
    this._el_68 = import4.createRenderElement(this.renderer,this._el_50,'li',import4.EMPTY_INLINE_ARRAY,this.debug(68,24,12));
    this._text_69 = this.renderer.createText(this._el_68,'Compose the containers (run next to the compose file)',this.debug(69,24,16));
    this._el_70 = import4.createRenderElement(this.renderer,this._el_68,'br',import4.EMPTY_INLINE_ARRAY,this.debug(70,24,69));
    this._el_71 = import4.createRenderElement(this.renderer,this._el_68,'pre',import4.EMPTY_INLINE_ARRAY,this.debug(71,24,73));
    this._text_72 = this.renderer.createText(this._el_71,'$ docker-compose up -d',this.debug(72,24,78));
    this._text_73 = this.renderer.createText(this._el_50,'\n            ',this.debug(73,24,111));
    this._el_74 = import4.createRenderElement(this.renderer,this._el_50,'li',import4.EMPTY_INLINE_ARRAY,this.debug(74,25,12));
    this._text_75 = this.renderer.createText(this._el_74,'Your server is installed. Check that if it\'s working correctly',this.debug(75,25,16));
    this._text_76 = this.renderer.createText(this._el_50,'\n        ',this.debug(76,25,83));
    this._text_77 = this.renderer.createText(this._el_28,'\n        ',this.debug(77,26,13));
    this._el_78 = import4.createRenderElement(this.renderer,this._el_28,'h2',new import4.InlineArray2(2,'id','api-activation'),this.debug(78,27,8));
    this._text_79 = this.renderer.createText(this._el_78,'API activation',this.debug(79,27,32));
    this._text_80 = this.renderer.createText(this._el_28,'\n        ',this.debug(80,27,51));
    this._el_81 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(81,28,8));
    this._text_82 = this.renderer.createText(this._el_81,'Open your Slamby API server at http://api_url/setup.',this.debug(82,28,11));
    this._text_83 = this.renderer.createText(this._el_28,'\n        ',this.debug(83,28,67));
    this._el_84 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(84,29,8));
    this._text_85 = this.renderer.createText(this._el_84,'Great, you have an installed Slamby API. Now your first step is the activation process.',this.debug(85,29,11));
    this._el_86 = import4.createRenderElement(this.renderer,this._el_84,'br',import4.EMPTY_INLINE_ARRAY,this.debug(86,29,98));
    this._text_87 = this.renderer.createText(this._el_84,'\n        During the setup process you need to:',this.debug(87,29,102));
    this._text_88 = this.renderer.createText(this._el_28,'\n        ',this.debug(88,30,49));
    this._el_89 = import4.createRenderElement(this.renderer,this._el_28,'ul',import4.EMPTY_INLINE_ARRAY,this.debug(89,31,8));
    this._text_90 = this.renderer.createText(this._el_89,'\n            ',this.debug(90,31,12));
    this._el_91 = import4.createRenderElement(this.renderer,this._el_89,'li',import4.EMPTY_INLINE_ARRAY,this.debug(91,32,12));
    this._text_92 = this.renderer.createText(this._el_91,'Request a Slamby License,',this.debug(92,32,16));
    this._text_93 = this.renderer.createText(this._el_89,'\n            ',this.debug(93,32,46));
    this._el_94 = import4.createRenderElement(this.renderer,this._el_89,'li',import4.EMPTY_INLINE_ARRAY,this.debug(94,33,12));
    this._text_95 = this.renderer.createText(this._el_94,'Copy your Slamby API License,',this.debug(95,33,16));
    this._text_96 = this.renderer.createText(this._el_89,'\n            ',this.debug(96,33,50));
    this._el_97 = import4.createRenderElement(this.renderer,this._el_89,'li',import4.EMPTY_INLINE_ARRAY,this.debug(97,34,12));
    this._text_98 = this.renderer.createText(this._el_97,'and set the secret (password) for your Slamby API.',this.debug(98,34,16));
    this._text_99 = this.renderer.createText(this._el_89,'\n            ',this.debug(99,34,71));
    this._el_100 = import4.createRenderElement(this.renderer,this._el_89,'li',import4.EMPTY_INLINE_ARRAY,this.debug(100,35,12));
    this._text_101 = this.renderer.createText(this._el_100,'Continue with the API activation.',this.debug(101,35,16));
    this._text_102 = this.renderer.createText(this._el_89,'\n        ',this.debug(102,35,54));
    this._text_103 = this.renderer.createText(this._el_28,'\n        ',this.debug(103,36,13));
    this._el_104 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(104,37,8));
    this._el_105 = import4.createRenderElement(this.renderer,this._el_104,'i',import4.EMPTY_INLINE_ARRAY,this.debug(105,37,11));
    this._text_106 = this.renderer.createText(this._el_105,'License',this.debug(106,37,14));
    this._el_107 = import4.createRenderElement(this.renderer,this._el_104,'br',import4.EMPTY_INLINE_ARRAY,this.debug(107,37,25));
    this._text_108 = this.renderer.createText(this._el_104,'\n        For open-source projects, you can use an `open-source license` for free, or for commercial purpose you can use a commercial license.',this.debug(108,37,29));
    this._text_109 = this.renderer.createText(this._el_28,'\n        ',this.debug(109,38,144));
    this._el_110 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(110,39,8));
    this._text_111 = this.renderer.createText(this._el_110,'For open-source license, your can request one from the setup wizard directly by typing your e-mail address and click the `Request a License` button. Our license service will generate an open-sourced license for you and will send it via email to the given email address.',this.debug(111,39,11));
    this._text_112 = this.renderer.createText(this._el_28,'\n        ',this.debug(112,39,284));
    this._el_113 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(113,40,8));
    this._text_114 = this.renderer.createText(this._el_113,'When your product or company is not open-sourced you cannot use Slamby API with open-source license; you need to purchase a `commercial license`. The pricing is based on the processor core number.',this.debug(114,40,11));
    this._text_115 = this.renderer.createText(this._el_28,'\n        ',this.debug(115,40,211));
    this._el_116 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(116,41,8));
    this._text_117 = this.renderer.createText(this._el_116,'For pricing details, please check our pricing ',this.debug(117,41,11));
    this._el_118 = import4.createRenderElement(this.renderer,this._el_116,'a',new import4.InlineArray2(2,'href','https://www.slamby.com/pricing'),this.debug(118,41,57));
    this._text_119 = this.renderer.createText(this._el_118,'https://www.slamby.com/pricing',this.debug(119,41,98));
    this._text_120 = this.renderer.createText(this._el_28,'\n        ',this.debug(120,41,136));
    this._el_121 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(121,42,8));
    this._text_122 = this.renderer.createText(this._el_121,'For purchasing a commercial license contact our ',this.debug(122,42,11));
    this._el_123 = import4.createRenderElement(this.renderer,this._el_121,'a',new import4.InlineArray2(2,'href','sales@slamby.com'),this.debug(123,42,59));
    this._text_124 = this.renderer.createText(this._el_123,'sales@slamby.com',this.debug(124,42,86));
    this._text_125 = this.renderer.createText(this._el_28,'\n        ',this.debug(125,42,110));
    this._el_126 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(126,43,8));
    this._el_127 = import4.createRenderElement(this.renderer,this._el_126,'i',import4.EMPTY_INLINE_ARRAY,this.debug(127,43,11));
    this._text_128 = this.renderer.createText(this._el_127,'API secret',this.debug(128,43,14));
    this._el_129 = import4.createRenderElement(this.renderer,this._el_126,'br',import4.EMPTY_INLINE_ARRAY,this.debug(129,43,28));
    this._text_130 = this.renderer.createText(this._el_126,'\n            Image',this.debug(130,43,32));
    this._text_131 = this.renderer.createText(this._el_28,'\n        ',this.debug(131,44,21));
    this._el_132 = import4.createRenderElement(this.renderer,this._el_28,'h2',new import4.InlineArray2(2,'id','slamby-insight'),this.debug(132,45,8));
    this._text_133 = this.renderer.createText(this._el_132,'Using Slamby Insight to manage your API',this.debug(133,45,32));
    this._text_134 = this.renderer.createText(this._el_28,'\n        ',this.debug(134,45,76));
    this._el_135 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(135,46,8));
    this._text_136 = this.renderer.createText(this._el_135,'For you Slamby API we have an excellent desktop application that makes the management jobs smoother, faster and easier. You can download it from here:',this.debug(136,46,11));
    this._text_137 = this.renderer.createText(this._el_28,'\n        ',this.debug(137,46,165));
    this._el_138 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(138,47,8));
    this._el_139 = import4.createRenderElement(this.renderer,this._el_138,'a',new import4.InlineArray16(10,'angulartics2On','click','angularticsCategory','getting-started-page','angularticsEvent','insight-download-btn','class','btn btn-default','href','https://insight.slamby.com/download'),this.debug(139,47,11));
    this._text_140 = this.renderer.createText(this._el_139,'Download',this.debug(140,47,187));
    this._text_141 = this.renderer.createText(this._el_138,'.',this.debug(141,47,199));
    this._text_142 = this.renderer.createText(this._el_28,'\n        ',this.debug(142,47,204));
    this._el_143 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(143,48,8));
    this._text_144 = this.renderer.createText(this._el_143,'For more information about how to use Insight check the online tutorial here: ',this.debug(144,48,11));
    this._el_145 = import4.createRenderElement(this.renderer,this._el_143,'a',new import4.InlineArray4(4,'href','https://developers.slamby.com/docs/Insight/','target','_blank'),this.debug(145,48,89));
    this._text_146 = this.renderer.createText(this._el_145,'https://developers.slamby.com/docs/Insight/',this.debug(146,48,159));
    this._text_147 = this.renderer.createText(this._el_28,'\n        ',this.debug(147,48,210));
    this._el_148 = import4.createRenderElement(this.renderer,this._el_28,'h2',new import4.InlineArray2(2,'id','integration'),this.debug(148,49,8));
    this._text_149 = this.renderer.createText(this._el_148,'Integration (SDKs)',this.debug(149,49,29));
    this._text_150 = this.renderer.createText(this._el_28,'\n        ',this.debug(150,49,52));
    this._el_151 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(151,50,8));
    this._text_152 = this.renderer.createText(this._el_151,'Now you have a working Slamby API, but how can you integrate it into your business processes? Slamby API has a very detailed Rest API that you can easily manage. For the full API documentation, please check the API developers page here: ',this.debug(152,50,11));
    this._el_153 = import4.createRenderElement(this.renderer,this._el_151,'a',new import4.InlineArray4(4,'href','https://developers.slamby.com/docs/API/','target','_blank'),this.debug(153,50,248));
    this._text_154 = this.renderer.createText(this._el_153,'https://developers.slamby.com/docs/API/',this.debug(154,50,314));
    this._text_155 = this.renderer.createText(this._el_28,'\n        ',this.debug(155,50,361));
    this._el_156 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(156,51,8));
    this._text_157 = this.renderer.createText(this._el_156,'\n            ',this.debug(157,51,11));
    this._el_158 = import4.createRenderElement(this.renderer,this._el_156,'i',import4.EMPTY_INLINE_ARRAY,this.debug(158,52,12));
    this._text_159 = this.renderer.createText(this._el_158,'A lovely gift from Slamby',this.debug(159,52,15));
    this._el_160 = import4.createRenderElement(this.renderer,this._el_156,'br',import4.EMPTY_INLINE_ARRAY,this.debug(160,52,44));
    this._text_161 = this.renderer.createText(this._el_156,'\n            We would like to make your job easier; that\'s why we work on five different SDKs. Please check the available versions, sources, and the readmes.\n        ',this.debug(161,52,48));
    this._text_162 = this.renderer.createText(this._el_28,'\n        ',this.debug(162,54,12));
    this._el_163 = import4.createRenderElement(this.renderer,this._el_28,'table',new import4.InlineArray2(2,'class','table table-striped'),this.debug(163,55,8));
    this._text_164 = this.renderer.createText(this._el_163,'\n            ',this.debug(164,55,43));
    this._el_165 = import4.createRenderElement(this.renderer,this._el_163,'thead',import4.EMPTY_INLINE_ARRAY,this.debug(165,56,12));
    this._text_166 = this.renderer.createText(this._el_165,'\n                ',this.debug(166,56,19));
    this._el_167 = import4.createRenderElement(this.renderer,this._el_165,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(167,57,16));
    this._text_168 = this.renderer.createText(this._el_167,'\n                    ',this.debug(168,57,20));
    this._el_169 = import4.createRenderElement(this.renderer,this._el_167,'td',import4.EMPTY_INLINE_ARRAY,this.debug(169,58,20));
    this._text_170 = this.renderer.createText(this._el_169,'SDK Name',this.debug(170,58,24));
    this._text_171 = this.renderer.createText(this._el_167,'\n                    ',this.debug(171,58,37));
    this._el_172 = import4.createRenderElement(this.renderer,this._el_167,'td',import4.EMPTY_INLINE_ARRAY,this.debug(172,59,20));
    this._text_173 = this.renderer.createText(this._el_172,'Download link and readme',this.debug(173,59,24));
    this._text_174 = this.renderer.createText(this._el_167,'\n                ',this.debug(174,59,53));
    this._text_175 = this.renderer.createText(this._el_165,'\n            ',this.debug(175,60,21));
    this._text_176 = this.renderer.createText(this._el_163,'\n            ',this.debug(176,61,20));
    this._el_177 = import4.createRenderElement(this.renderer,this._el_163,'tbody',import4.EMPTY_INLINE_ARRAY,this.debug(177,62,12));
    this._text_178 = this.renderer.createText(this._el_177,'\n                ',this.debug(178,62,19));
    this._el_179 = import4.createRenderElement(this.renderer,this._el_177,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(179,63,16));
    this._text_180 = this.renderer.createText(this._el_179,'\n                    ',this.debug(180,63,20));
    this._el_181 = import4.createRenderElement(this.renderer,this._el_179,'td',import4.EMPTY_INLINE_ARRAY,this.debug(181,64,20));
    this._text_182 = this.renderer.createText(this._el_181,'.Net',this.debug(182,64,24));
    this._text_183 = this.renderer.createText(this._el_179,'\n                    ',this.debug(183,64,33));
    this._el_184 = import4.createRenderElement(this.renderer,this._el_179,'td',import4.EMPTY_INLINE_ARRAY,this.debug(184,65,20));
    this._el_185 = import4.createRenderElement(this.renderer,this._el_184,'a',new import4.InlineArray4(4,'href','https://github.com/slamby/slamby-sdk-net','target','_blank'),this.debug(185,65,24));
    this._text_186 = this.renderer.createText(this._el_185,'https://github.com/slamby/slamby-sdk-net',this.debug(186,65,91));
    this._text_187 = this.renderer.createText(this._el_179,'\n                ',this.debug(187,65,140));
    this._text_188 = this.renderer.createText(this._el_177,'\n                ',this.debug(188,66,21));
    this._el_189 = import4.createRenderElement(this.renderer,this._el_177,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(189,67,16));
    this._text_190 = this.renderer.createText(this._el_189,'\n                    ',this.debug(190,67,20));
    this._el_191 = import4.createRenderElement(this.renderer,this._el_189,'td',import4.EMPTY_INLINE_ARRAY,this.debug(191,68,20));
    this._text_192 = this.renderer.createText(this._el_191,'JavaScript',this.debug(192,68,24));
    this._text_193 = this.renderer.createText(this._el_189,'\n                    ',this.debug(193,68,39));
    this._el_194 = import4.createRenderElement(this.renderer,this._el_189,'td',import4.EMPTY_INLINE_ARRAY,this.debug(194,69,20));
    this._el_195 = import4.createRenderElement(this.renderer,this._el_194,'a',new import4.InlineArray4(4,'href','https://github.com/slamby/slamby-sdk-javascript','target','_blank'),this.debug(195,69,24));
    this._text_196 = this.renderer.createText(this._el_195,'https://github.com/slamby/slamby-sdk-javascript',this.debug(196,69,98));
    this._text_197 = this.renderer.createText(this._el_189,'\n                ',this.debug(197,69,154));
    this._text_198 = this.renderer.createText(this._el_177,'\n                ',this.debug(198,70,21));
    this._el_199 = import4.createRenderElement(this.renderer,this._el_177,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(199,71,16));
    this._text_200 = this.renderer.createText(this._el_199,'\n                    ',this.debug(200,71,20));
    this._el_201 = import4.createRenderElement(this.renderer,this._el_199,'td',import4.EMPTY_INLINE_ARRAY,this.debug(201,72,20));
    this._text_202 = this.renderer.createText(this._el_201,'Python',this.debug(202,72,24));
    this._text_203 = this.renderer.createText(this._el_199,'\n                    ',this.debug(203,72,35));
    this._el_204 = import4.createRenderElement(this.renderer,this._el_199,'td',import4.EMPTY_INLINE_ARRAY,this.debug(204,73,20));
    this._el_205 = import4.createRenderElement(this.renderer,this._el_204,'a',new import4.InlineArray4(4,'href','https://github.com/slamby/slamby-sdk-python','target','_blank'),this.debug(205,73,24));
    this._text_206 = this.renderer.createText(this._el_205,'https://github.com/slamby/slamby-sdk-python',this.debug(206,73,94));
    this._text_207 = this.renderer.createText(this._el_199,'\n                ',this.debug(207,73,146));
    this._text_208 = this.renderer.createText(this._el_177,'\n                ',this.debug(208,74,21));
    this._el_209 = import4.createRenderElement(this.renderer,this._el_177,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(209,75,16));
    this._text_210 = this.renderer.createText(this._el_209,'\n                    ',this.debug(210,75,20));
    this._el_211 = import4.createRenderElement(this.renderer,this._el_209,'td',import4.EMPTY_INLINE_ARRAY,this.debug(211,76,20));
    this._text_212 = this.renderer.createText(this._el_211,'PHP',this.debug(212,76,24));
    this._text_213 = this.renderer.createText(this._el_209,'\n                    ',this.debug(213,76,32));
    this._el_214 = import4.createRenderElement(this.renderer,this._el_209,'td',import4.EMPTY_INLINE_ARRAY,this.debug(214,77,20));
    this._el_215 = import4.createRenderElement(this.renderer,this._el_214,'a',new import4.InlineArray4(4,'href','https://github.com/slamby/slamby-sdk-php','target','_blank'),this.debug(215,77,24));
    this._text_216 = this.renderer.createText(this._el_215,'https://github.com/slamby/slamby-sdk-php',this.debug(216,77,91));
    this._text_217 = this.renderer.createText(this._el_209,'\n                ',this.debug(217,77,140));
    this._text_218 = this.renderer.createText(this._el_177,'\n                ',this.debug(218,78,21));
    this._el_219 = import4.createRenderElement(this.renderer,this._el_177,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(219,79,16));
    this._text_220 = this.renderer.createText(this._el_219,'\n                    ',this.debug(220,79,20));
    this._el_221 = import4.createRenderElement(this.renderer,this._el_219,'td',import4.EMPTY_INLINE_ARRAY,this.debug(221,80,20));
    this._text_222 = this.renderer.createText(this._el_221,'Angular 2',this.debug(222,80,24));
    this._text_223 = this.renderer.createText(this._el_219,'\n                    ',this.debug(223,80,38));
    this._el_224 = import4.createRenderElement(this.renderer,this._el_219,'td',import4.EMPTY_INLINE_ARRAY,this.debug(224,81,20));
    this._el_225 = import4.createRenderElement(this.renderer,this._el_224,'a',new import4.InlineArray4(4,'href','https://github.com/slamby/slamby-sdk-angular2','target','_blank'),this.debug(225,81,24));
    this._text_226 = this.renderer.createText(this._el_225,'https://github.com/slamby/slamby-sdk-angular2',this.debug(226,81,96));
    this._text_227 = this.renderer.createText(this._el_219,'\n                ',this.debug(227,81,150));
    this._text_228 = this.renderer.createText(this._el_177,'\n            ',this.debug(228,82,21));
    this._text_229 = this.renderer.createText(this._el_163,'\n        ',this.debug(229,83,20));
    this._text_230 = this.renderer.createText(this._el_28,'\n        ',this.debug(230,84,16));
    this._el_231 = import4.createRenderElement(this.renderer,this._el_28,'h2',new import4.InlineArray2(2,'id','documentation'),this.debug(231,85,8));
    this._text_232 = this.renderer.createText(this._el_231,'Product documentation',this.debug(232,85,31));
    this._text_233 = this.renderer.createText(this._el_28,'\n        ',this.debug(233,85,57));
    this._el_234 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(234,86,8));
    this._text_235 = this.renderer.createText(this._el_234,'Here we go, all the Slamby products are now installed. But how can you use them? When you do an API integration, or you need to know specific settings, then please check the API documentation on our developer site: ',this.debug(235,86,11));
    this._el_236 = import4.createRenderElement(this.renderer,this._el_234,'a',new import4.InlineArray4(4,'href','https://developers.slamby.com/docs/API','target','_blank'),this.debug(236,86,226));
    this._text_237 = this.renderer.createText(this._el_236,'https://developers.slamby.com/docs/API',this.debug(237,86,291));
    this._text_238 = this.renderer.createText(this._el_234,',',this.debug(238,86,333));
    this._el_239 = import4.createRenderElement(this.renderer,this._el_234,'br',import4.EMPTY_INLINE_ARRAY,this.debug(239,86,334));
    this._text_240 = this.renderer.createText(this._el_234,'\n        or, check the other products documentation as well ',this.debug(240,86,338));
    this._el_241 = import4.createRenderElement(this.renderer,this._el_234,'a',new import4.InlineArray4(4,'href','https://developers.slamby.com','target','_blank'),this.debug(241,87,59));
    this._text_242 = this.renderer.createText(this._el_241,'https://developers.slamby.com',this.debug(242,87,115));
    this._text_243 = this.renderer.createText(this._el_28,'\n        ',this.debug(243,87,152));
    this._el_244 = import4.createRenderElement(this.renderer,this._el_28,'h2',new import4.InlineArray2(2,'id','support'),this.debug(244,88,8));
    this._text_245 = this.renderer.createText(this._el_244,'Support',this.debug(245,88,25));
    this._text_246 = this.renderer.createText(this._el_28,'\n        ',this.debug(246,88,37));
    this._el_247 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(247,89,8));
    this._text_248 = this.renderer.createText(this._el_247,'Slamby support mailing list for basic support: ',this.debug(248,89,11));
    this._el_249 = import4.createRenderElement(this.renderer,this._el_247,'a',new import4.InlineArray4(4,'href','https://groups.google.com/forum/#!forum/slamby','target','_blank'),this.debug(249,89,58));
    this._text_250 = this.renderer.createText(this._el_249,'https://groups.google.com/forum/#!forum/slamby',this.debug(250,89,131));
    this._text_251 = this.renderer.createText(this._el_28,'\n        ',this.debug(251,89,185));
    this._el_252 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(252,90,8));
    this._text_253 = this.renderer.createText(this._el_252,'Each Slamby license includes a `basic support` with absolutely no SLA. This means you can access our support via our online support mailing list and you can ask for help from our community. In this case, the reaction time is not guaranteed, and there is no direct access to our technical experts.',this.debug(253,90,11));
    this._text_254 = this.renderer.createText(this._el_28,'\n        ',this.debug(254,90,311));
    this._el_255 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(255,91,8));
    this._text_256 = this.renderer.createText(this._el_255,'When you need a `professional support`, please purchase one. Each professional support contains short-time SLAs and response time. Each professional support gives you direct access to our technical experts.',this.debug(256,91,11));
    this._text_257 = this.renderer.createText(this._el_28,'\n        ',this.debug(257,91,221));
    this._el_258 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(258,92,8));
    this._text_259 = this.renderer.createText(this._el_258,'For more details, please check our available support options here: ',this.debug(259,92,11));
    this._el_260 = import4.createRenderElement(this.renderer,this._el_258,'a',new import4.InlineArray4(4,'href','https://www.slamby.com/support','target','_blank'),this.debug(260,92,78));
    this._text_261 = this.renderer.createText(this._el_260,'https://www.slamby.com/support',this.debug(261,92,135));
    this._text_262 = this.renderer.createText(this._el_28,'\n        ',this.debug(262,92,173));
    this._el_263 = import4.createRenderElement(this.renderer,this._el_28,'p',import4.EMPTY_INLINE_ARRAY,this.debug(263,93,8));
    this._text_264 = this.renderer.createText(this._el_263,'And contact our sales: ',this.debug(264,93,11));
    this._el_265 = import4.createRenderElement(this.renderer,this._el_263,'a',new import4.InlineArray2(2,'href','sales@slamby.com'),this.debug(265,93,34));
    this._text_266 = this.renderer.createText(this._el_265,'sales@slamby.com',this.debug(266,93,61));
    this._text_267 = this.renderer.createText(this._el_28,'\n    ',this.debug(267,93,85));
    this._text_268 = this.renderer.createText(this._el_2,'\n',this.debug(268,94,10));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._text_103,
      this._el_104,
      this._el_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._text_109,
      this._el_110,
      this._text_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._text_115,
      this._el_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._text_120,
      this._el_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._text_125,
      this._el_126,
      this._el_127,
      this._text_128,
      this._el_129,
      this._text_130,
      this._text_131,
      this._el_132,
      this._text_133,
      this._text_134,
      this._el_135,
      this._text_136,
      this._text_137,
      this._el_138,
      this._el_139,
      this._text_140,
      this._text_141,
      this._text_142,
      this._el_143,
      this._text_144,
      this._el_145,
      this._text_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._text_150,
      this._el_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._text_155,
      this._el_156,
      this._text_157,
      this._el_158,
      this._text_159,
      this._el_160,
      this._text_161,
      this._text_162,
      this._el_163,
      this._text_164,
      this._el_165,
      this._text_166,
      this._el_167,
      this._text_168,
      this._el_169,
      this._text_170,
      this._text_171,
      this._el_172,
      this._text_173,
      this._text_174,
      this._text_175,
      this._text_176,
      this._el_177,
      this._text_178,
      this._el_179,
      this._text_180,
      this._el_181,
      this._text_182,
      this._text_183,
      this._el_184,
      this._el_185,
      this._text_186,
      this._text_187,
      this._text_188,
      this._el_189,
      this._text_190,
      this._el_191,
      this._text_192,
      this._text_193,
      this._el_194,
      this._el_195,
      this._text_196,
      this._text_197,
      this._text_198,
      this._el_199,
      this._text_200,
      this._el_201,
      this._text_202,
      this._text_203,
      this._el_204,
      this._el_205,
      this._text_206,
      this._text_207,
      this._text_208,
      this._el_209,
      this._text_210,
      this._el_211,
      this._text_212,
      this._text_213,
      this._el_214,
      this._el_215,
      this._text_216,
      this._text_217,
      this._text_218,
      this._el_219,
      this._text_220,
      this._el_221,
      this._text_222,
      this._text_223,
      this._el_224,
      this._el_225,
      this._text_226,
      this._text_227,
      this._text_228,
      this._text_229,
      this._text_230,
      this._el_231,
      this._text_232,
      this._text_233,
      this._el_234,
      this._text_235,
      this._el_236,
      this._text_237,
      this._text_238,
      this._el_239,
      this._text_240,
      this._el_241,
      this._text_242,
      this._text_243,
      this._el_244,
      this._text_245,
      this._text_246,
      this._el_247,
      this._text_248,
      this._el_249,
      this._text_250,
      this._text_251,
      this._el_252,
      this._text_253,
      this._text_254,
      this._el_255,
      this._text_256,
      this._text_257,
      this._el_258,
      this._text_259,
      this._el_260,
      this._text_261,
      this._text_262,
      this._el_263,
      this._text_264,
      this._el_265,
      this._text_266,
      this._text_267,
      this._text_268
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
}