/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './pricing.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './pricing.component.css.shim';
import * as import10 from '../common/header/header.component';
import * as import11 from '@angular/router/src/directives/router_link';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/common/src/directives/ng_for';
import * as import14 from '../common/header/header.component.ngfactory';
import * as import15 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import16 from '@angular/core/src/linker/view_container';
import * as import17 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import18 from '@angular/router/src/router';
import * as import19 from '@angular/router/src/router_state';
import * as import20 from '@angular/common/src/location/location_strategy';
import * as import21 from '@angular/core/src/change_detection/differs/iterable_differs';
export class Wrapper_PricingComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PricingComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.PricingComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const nodeDebugInfos_PricingComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.PricingComponent],import0.PricingComponent,{})];
var renderType_PricingComponent_Host:import3.RenderComponentType = import4.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_PricingComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PricingComponent>;
  _PricingComponent_0_3:Wrapper_PricingComponent;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PricingComponent_Host0,renderType_PricingComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_PricingComponent_Host0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ng-component',import4.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_PricingComponent0(this.viewUtils,this,0,this._el_0);
    this._PricingComponent_0_3 = new Wrapper_PricingComponent();
    this.compView_0.create(this._PricingComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._PricingComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PricingComponent) && (0 === requestNodeIndex))) { return this._PricingComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._PricingComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PricingComponentNgFactory:import8.ComponentFactory<import0.PricingComponent> = new import8.ComponentFactory<import0.PricingComponent>('ng-component',View_PricingComponent_Host0,import0.PricingComponent);
const styles_PricingComponent:any[] = [import9.styles];
const nodeDebugInfos_PricingComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo([import10.HeaderComponent],import10.HeaderComponent,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import11.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.TemplateRef,
    import13.NgFor
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import12.TemplateRef,
    import13.NgFor
  ]
  ,(null as any),{})
]
;
var renderType_PricingComponent:import3.RenderComponentType = import4.createRenderComponentType('/home/peter/Desktop/git/angular2-aot-webpack/src/app/pricing/pricing.component.html',0,import5.ViewEncapsulation.Emulated,styles_PricingComponent,{});
export class View_PricingComponent0 extends import1.DebugAppView<import0.PricingComponent> {
  _el_0:any;
  compView_0:import1.AppView<import10.HeaderComponent>;
  _HeaderComponent_0_3:import14.Wrapper_HeaderComponent;
  _el_1:any;
  _el_2:any;
  _el_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _RouterLinkWithHref_12_3:import15.Wrapper_RouterLinkWithHref;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _el_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _el_34:any;
  _el_35:any;
  _el_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _el_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _el_52:any;
  _el_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _el_69:any;
  _el_70:any;
  _el_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _el_78:any;
  _el_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _el_88:any;
  _el_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _el_95:any;
  _el_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _el_102:any;
  _el_103:any;
  _el_104:any;
  _el_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _el_109:any;
  _el_110:any;
  _text_111:any;
  _el_112:any;
  _text_113:any;
  _el_114:any;
  _text_115:any;
  _el_116:any;
  _el_117:any;
  _el_118:any;
  _el_119:any;
  _text_120:any;
  _el_121:any;
  _text_122:any;
  _el_123:any;
  _text_124:any;
  _el_125:any;
  _text_126:any;
  _el_127:any;
  _text_128:any;
  _el_129:any;
  _text_130:any;
  _el_131:any;
  _text_132:any;
  _el_133:any;
  _anchor_134:any;
  /*private*/ _vc_134:import16.ViewContainer;
  _TemplateRef_134_5:any;
  _NgFor_134_6:import17.Wrapper_NgFor;
  _el_135:any;
  _el_136:any;
  _el_137:any;
  _text_138:any;
  _el_139:any;
  _el_140:any;
  _el_141:any;
  _el_142:any;
  _text_143:any;
  _el_144:any;
  _text_145:any;
  _el_146:any;
  _text_147:any;
  _el_148:any;
  _text_149:any;
  _el_150:any;
  _text_151:any;
  _el_152:any;
  _text_153:any;
  _el_154:any;
  _text_155:any;
  _el_156:any;
  _anchor_157:any;
  /*private*/ _vc_157:import16.ViewContainer;
  _TemplateRef_157_5:any;
  _NgFor_157_6:import17.Wrapper_NgFor;
  _arr_167:any;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PricingComponent0,renderType_PricingComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_PricingComponent0);
    this._arr_167 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'pm-header',import4.EMPTY_INLINE_ARRAY,this.debug(0,0,0));
    this.compView_0 = new import14.View_HeaderComponent0(this.viewUtils,this,0,this._el_0);
    this._HeaderComponent_0_3 = new import14.Wrapper_HeaderComponent();
    this.compView_0.create(this._HeaderComponent_0_3.context);
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'section',new import4.InlineArray2(2,'class','main'),this.debug(1,0,23));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_1,'div',new import4.InlineArray2(2,'class','container'),this.debug(2,0,45));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','body'),this.debug(3,0,68));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_3,'div',new import4.InlineArray2(2,'class','main-message'),this.debug(4,0,86));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_4,'h1',import4.EMPTY_INLINE_ARRAY,this.debug(5,0,112));
    this._text_6 = this.renderer.createText(this._el_5,'45 € / core / month',this.debug(6,0,116));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_4,'p',new import4.InlineArray2(2,'class','lead'),this.debug(7,0,140));
    this._text_8 = this.renderer.createText(this._el_7,'Start using Slamby for a price of a cup of coffee per core. Use it as a SaaS or install it on your machine.',this.debug(8,0,156));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_4,'p',new import4.InlineArray2(2,'class','lead'),this.debug(9,0,267));
    this._text_10 = this.renderer.createText(this._el_9,'No query limit, no memory limit',this.debug(10,0,283));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_4,'p',import4.EMPTY_INLINE_ARRAY,this.debug(11,0,318));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_11,'a',new import4.InlineArray8(8,'angulartics2On','click','angularticsCategory','pricing-page','angularticsEvent','getting-started-click','class','btn btn-default btn-lg'),this.debug(12,0,321));
    this._RouterLinkWithHref_12_3 = new import15.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import18.Router,this.parentIndex),this.parentView.injectorGet(import19.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import20.LocationStrategy,this.parentIndex));
    this._text_13 = this.renderer.createText(this._el_12,'Getting started',this.debug(13,0,490));
    this._el_14 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),this.debug(14,0,541));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_14,'div',new import4.InlineArray2(2,'class','row'),this.debug(15,0,564));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_15,'div',new import4.InlineArray2(2,'class','col-md-12'),this.debug(16,0,581));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_16,'h1',new import4.InlineArray2(2,'class','page-header'),this.debug(17,0,604));
    this._text_18 = this.renderer.createText(this._el_17,'Pricing',this.debug(18,0,628));
    this._el_19 = import4.createRenderElement(this.renderer,this._el_16,'p',new import4.InlineArray2(2,'class','lead'),this.debug(19,0,640));
    this._text_20 = this.renderer.createText(this._el_19,'Our product is available for both private hosting and SaaS. You can easily download and install it on your machine, or purchase it as a monthly service.',this.debug(20,0,656));
    this._el_21 = import4.createRenderElement(this.renderer,this._el_16,'p',new import4.InlineArray2(2,'class','lead'),this.debug(21,0,812));
    this._text_22 = this.renderer.createText(this._el_21,'For private hosting, you can download and install Slamby API and register it with an open-source license for free, and you can purchase a core-based license for commercial use.',this.debug(22,0,828));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_16,'p',new import4.InlineArray2(2,'class','lead'),this.debug(23,0,1008));
    this._text_24 = this.renderer.createText(this._el_23,'For SaaS, you can select a required instance size and buy it with a monthly payment. The prices cover the standard Slamby license per core + hosting fee.',this.debug(24,0,1024));
    this._el_25 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),this.debug(25,0,1199));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_25,'div',new import4.InlineArray2(2,'class','row'),this.debug(26,0,1222));
    this._el_27 = import4.createRenderElement(this.renderer,this._el_26,'div',new import4.InlineArray2(2,'class','col-md-12'),this.debug(27,0,1239));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_27,'h1',new import4.InlineArray2(2,'class','page-header'),this.debug(28,0,1262));
    this._text_29 = this.renderer.createText(this._el_28,'Core pricing',this.debug(29,0,1286));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_26,'div',new import4.InlineArray2(2,'class','col-md-6'),this.debug(30,0,1309));
    this._el_31 = import4.createRenderElement(this.renderer,this._el_30,'p',new import4.InlineArray2(2,'class','lead'),this.debug(31,0,1331));
    this._text_32 = this.renderer.createText(this._el_31,'Standard Slamby API pricing, based on the  processor core number. There is no query, usage, storage and memory limitation.',this.debug(32,0,1347));
    this._el_33 = import4.createRenderElement(this.renderer,this._el_26,'div',new import4.InlineArray2(2,'class','col-md-6'),this.debug(33,0,1479));
    this._el_34 = import4.createRenderElement(this.renderer,this._el_33,'table',new import4.InlineArray2(2,'class','table table-striped'),this.debug(34,0,1501));
    this._el_35 = import4.createRenderElement(this.renderer,this._el_34,'thead',import4.EMPTY_INLINE_ARRAY,this.debug(35,0,1536));
    this._el_36 = import4.createRenderElement(this.renderer,this._el_35,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(36,0,1543));
    this._el_37 = import4.createRenderElement(this.renderer,this._el_36,'th',import4.EMPTY_INLINE_ARRAY,this.debug(37,0,1547));
    this._text_38 = this.renderer.createText(this._el_37,'Name',this.debug(38,0,1551));
    this._el_39 = import4.createRenderElement(this.renderer,this._el_36,'th',import4.EMPTY_INLINE_ARRAY,this.debug(39,0,1560));
    this._text_40 = this.renderer.createText(this._el_39,'Description',this.debug(40,0,1564));
    this._el_41 = import4.createRenderElement(this.renderer,this._el_36,'th',import4.EMPTY_INLINE_ARRAY,this.debug(41,0,1580));
    this._text_42 = this.renderer.createText(this._el_41,'price',this.debug(42,0,1584));
    this._el_43 = import4.createRenderElement(this.renderer,this._el_34,'tbody',import4.EMPTY_INLINE_ARRAY,this.debug(43,0,1607));
    this._el_44 = import4.createRenderElement(this.renderer,this._el_43,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(44,0,1614));
    this._el_45 = import4.createRenderElement(this.renderer,this._el_44,'td',import4.EMPTY_INLINE_ARRAY,this.debug(45,0,1618));
    this._text_46 = this.renderer.createText(this._el_45,'1 core license',this.debug(46,0,1622));
    this._el_47 = import4.createRenderElement(this.renderer,this._el_44,'td',import4.EMPTY_INLINE_ARRAY,this.debug(47,0,1641));
    this._text_48 = this.renderer.createText(this._el_47,'unlimited memory, unlimited storage',this.debug(48,0,1645));
    this._el_49 = import4.createRenderElement(this.renderer,this._el_44,'td',import4.EMPTY_INLINE_ARRAY,this.debug(49,0,1685));
    this._text_50 = this.renderer.createText(this._el_49,'45 € / processor core / month',this.debug(50,0,1689));
    this._el_51 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),this.debug(51,0,1762));
    this._el_52 = import4.createRenderElement(this.renderer,this._el_51,'div',new import4.InlineArray2(2,'class','row'),this.debug(52,0,1785));
    this._el_53 = import4.createRenderElement(this.renderer,this._el_52,'div',new import4.InlineArray2(2,'class','col-md-12'),this.debug(53,0,1802));
    this._el_54 = import4.createRenderElement(this.renderer,this._el_53,'h2',new import4.InlineArray2(2,'class','page-header'),this.debug(54,0,1825));
    this._text_55 = this.renderer.createText(this._el_54,'Support',this.debug(55,0,1849));
    this._el_56 = import4.createRenderElement(this.renderer,this._el_52,'div',new import4.InlineArray2(2,'class','col-md-6'),this.debug(56,0,1867));
    this._el_57 = import4.createRenderElement(this.renderer,this._el_56,'p',new import4.InlineArray2(2,'class','lead'),this.debug(57,0,1889));
    this._text_58 = this.renderer.createText(this._el_57,'For professional use select one of our available support options based on the available communication channels and SLA.',this.debug(58,0,1905));
    this._el_59 = import4.createRenderElement(this.renderer,this._el_56,'p',new import4.InlineArray2(2,'class','lead'),this.debug(59,0,2028));
    this._text_60 = this.renderer.createText(this._el_59,'Currently, we have three type of support options. Each Slamby instance has a basic support option that includes community-based - forum support.',this.debug(60,0,2044));
    this._el_61 = import4.createRenderElement(this.renderer,this._el_56,'p',import4.EMPTY_INLINE_ARRAY,this.debug(61,0,2192));
    this._el_62 = import4.createRenderElement(this.renderer,this._el_61,'a',new import4.InlineArray8(8,'angulartics2On','click','angularticsCategory','pricing-page','angularticsEvent','support-get-mode-information','href','mailto:sales@slamby.com'),this.debug(62,0,2195));
    this._text_63 = this.renderer.createText(this._el_62,'Get more information',this.debug(63,0,2335));
    this._el_64 = import4.createRenderElement(this.renderer,this._el_56,'p',import4.EMPTY_INLINE_ARRAY,this.debug(64,0,2363));
    this._text_65 = this.renderer.createText(this._el_64,'Community support:',this.debug(65,0,2366));
    this._el_66 = import4.createRenderElement(this.renderer,this._el_64,'a',new import4.InlineArray4(4,'href','https://groups.google.com/forum/#!forum/slamby','target','_blank'),this.debug(66,0,2384));
    this._text_67 = this.renderer.createText(this._el_66,'https://groups.google.com/forum/#!forum/slamby',this.debug(67,0,2457));
    this._el_68 = import4.createRenderElement(this.renderer,this._el_52,'div',new import4.InlineArray2(2,'class','col-md-6'),this.debug(68,0,2517));
    this._el_69 = import4.createRenderElement(this.renderer,this._el_68,'table',new import4.InlineArray2(2,'class','table table-striped'),this.debug(69,0,2539));
    this._el_70 = import4.createRenderElement(this.renderer,this._el_69,'thead',import4.EMPTY_INLINE_ARRAY,this.debug(70,0,2574));
    this._el_71 = import4.createRenderElement(this.renderer,this._el_70,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(71,0,2581));
    this._el_72 = import4.createRenderElement(this.renderer,this._el_71,'th',import4.EMPTY_INLINE_ARRAY,this.debug(72,0,2585));
    this._text_73 = this.renderer.createText(this._el_72,'Name',this.debug(73,0,2589));
    this._el_74 = import4.createRenderElement(this.renderer,this._el_71,'th',import4.EMPTY_INLINE_ARRAY,this.debug(74,0,2598));
    this._text_75 = this.renderer.createText(this._el_74,'Description',this.debug(75,0,2602));
    this._el_76 = import4.createRenderElement(this.renderer,this._el_71,'th',import4.EMPTY_INLINE_ARRAY,this.debug(76,0,2618));
    this._text_77 = this.renderer.createText(this._el_76,'price',this.debug(77,0,2622));
    this._el_78 = import4.createRenderElement(this.renderer,this._el_69,'tbody',import4.EMPTY_INLINE_ARRAY,this.debug(78,0,2645));
    this._el_79 = import4.createRenderElement(this.renderer,this._el_78,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(79,0,2652));
    this._el_80 = import4.createRenderElement(this.renderer,this._el_79,'td',import4.EMPTY_INLINE_ARRAY,this.debug(80,0,2656));
    this._text_81 = this.renderer.createText(this._el_80,'Basic',this.debug(81,0,2660));
    this._el_82 = import4.createRenderElement(this.renderer,this._el_79,'td',import4.EMPTY_INLINE_ARRAY,this.debug(82,0,2670));
    this._el_83 = import4.createRenderElement(this.renderer,this._el_82,'a',new import4.InlineArray4(4,'href','https://groups.google.com/forum/#!forum/slamby','target','_blank'),this.debug(83,0,2674));
    this._text_84 = this.renderer.createText(this._el_83,'Community only',this.debug(84,0,2747));
    this._text_85 = this.renderer.createText(this._el_82,',no SLA',this.debug(85,0,2765));
    this._el_86 = import4.createRenderElement(this.renderer,this._el_79,'td',import4.EMPTY_INLINE_ARRAY,this.debug(86,0,2777));
    this._text_87 = this.renderer.createText(this._el_86,'Free',this.debug(87,0,2781));
    this._el_88 = import4.createRenderElement(this.renderer,this._el_78,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(88,0,2795));
    this._el_89 = import4.createRenderElement(this.renderer,this._el_88,'td',import4.EMPTY_INLINE_ARRAY,this.debug(89,0,2799));
    this._text_90 = this.renderer.createText(this._el_89,'Professional',this.debug(90,0,2803));
    this._el_91 = import4.createRenderElement(this.renderer,this._el_88,'td',import4.EMPTY_INLINE_ARRAY,this.debug(91,0,2820));
    this._text_92 = this.renderer.createText(this._el_91,'Next workday, email',this.debug(92,0,2824));
    this._el_93 = import4.createRenderElement(this.renderer,this._el_88,'td',import4.EMPTY_INLINE_ARRAY,this.debug(93,0,2848));
    this._text_94 = this.renderer.createText(this._el_93,'2000 € yearly / instance',this.debug(94,0,2852));
    this._el_95 = import4.createRenderElement(this.renderer,this._el_78,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(95,0,2886));
    this._el_96 = import4.createRenderElement(this.renderer,this._el_95,'td',import4.EMPTY_INLINE_ARRAY,this.debug(96,0,2890));
    this._text_97 = this.renderer.createText(this._el_96,'Production',this.debug(97,0,2894));
    this._el_98 = import4.createRenderElement(this.renderer,this._el_95,'td',import4.EMPTY_INLINE_ARRAY,this.debug(98,0,2909));
    this._text_99 = this.renderer.createText(this._el_98,'Direct developer and technical access, 5 hours SLA, email, skype, phone.',this.debug(99,0,2913));
    this._el_100 = import4.createRenderElement(this.renderer,this._el_95,'td',import4.EMPTY_INLINE_ARRAY,this.debug(100,0,2990));
    this._text_101 = this.renderer.createText(this._el_100,'6000 € yearly / instance',this.debug(101,0,2994));
    this._el_102 = import4.createRenderElement(this.renderer,this._el_52,'div',new import4.InlineArray2(2,'class','container pricing'),this.debug(102,0,3050));
    this._el_103 = import4.createRenderElement(this.renderer,this._el_102,'div',new import4.InlineArray2(2,'class','row'),this.debug(103,0,3081));
    this._el_104 = import4.createRenderElement(this.renderer,this._el_103,'div',new import4.InlineArray2(2,'class','col-md-12'),this.debug(104,0,3098));
    this._el_105 = import4.createRenderElement(this.renderer,this._el_104,'h2',new import4.InlineArray2(2,'class','page-header'),this.debug(105,0,3121));
    this._text_106 = this.renderer.createText(this._el_105,'SaaS pricing',this.debug(106,0,3145));
    this._el_107 = import4.createRenderElement(this.renderer,this._el_104,'p',new import4.InlineArray2(2,'class','lead'),this.debug(107,0,3162));
    this._text_108 = this.renderer.createText(this._el_107,'Purchase Slamby as software as a service. Select one of our hosting locations and one suitable size of the instance. Prices based on the resource size + core based Slamby license fee.',this.debug(108,0,3178));
    this._el_109 = import4.createRenderElement(this.renderer,this._el_104,'p',import4.EMPTY_INLINE_ARRAY,this.debug(109,0,3365));
    this._el_110 = import4.createRenderElement(this.renderer,this._el_109,'a',new import4.InlineArray16(10,'angulartics2On','click','angularticsCategory','pricing-page','angularticsEvent','sas-contact-sales','class','btn btn-default','href','mailto:sales@slamby.com'),this.debug(110,0,3368));
    this._text_111 = this.renderer.createText(this._el_110,'Contact sales',this.debug(111,0,3521));
    this._el_112 = import4.createRenderElement(this.renderer,this._el_104,'p',import4.EMPTY_INLINE_ARRAY,this.debug(112,0,3542));
    this._text_113 = this.renderer.createText(this._el_112,'Prices are in € per month',this.debug(113,0,3545));
    this._el_114 = import4.createRenderElement(this.renderer,this._el_104,'h3',import4.EMPTY_INLINE_ARRAY,this.debug(114,0,3574));
    this._text_115 = this.renderer.createText(this._el_114,'European',this.debug(115,0,3578));
    this._el_116 = import4.createRenderElement(this.renderer,this._el_104,'table',new import4.InlineArray2(2,'class','table table-striped'),this.debug(116,0,3591));
    this._el_117 = import4.createRenderElement(this.renderer,this._el_116,'thead',import4.EMPTY_INLINE_ARRAY,this.debug(117,0,3626));
    this._el_118 = import4.createRenderElement(this.renderer,this._el_117,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(118,0,3633));
    this._el_119 = import4.createRenderElement(this.renderer,this._el_118,'th',import4.EMPTY_INLINE_ARRAY,this.debug(119,0,3637));
    this._text_120 = this.renderer.createText(this._el_119,'Name',this.debug(120,0,3641));
    this._el_121 = import4.createRenderElement(this.renderer,this._el_118,'th',import4.EMPTY_INLINE_ARRAY,this.debug(121,0,3650));
    this._text_122 = this.renderer.createText(this._el_121,'Core',this.debug(122,0,3654));
    this._el_123 = import4.createRenderElement(this.renderer,this._el_118,'th',import4.EMPTY_INLINE_ARRAY,this.debug(123,0,3663));
    this._text_124 = this.renderer.createText(this._el_123,'Memory',this.debug(124,0,3667));
    this._el_125 = import4.createRenderElement(this.renderer,this._el_118,'th',new import4.InlineArray2(2,'class','hidden-xs'),this.debug(125,0,3678));
    this._text_126 = this.renderer.createText(this._el_125,'Storage',this.debug(126,0,3700));
    this._el_127 = import4.createRenderElement(this.renderer,this._el_118,'th',new import4.InlineArray2(2,'class','hidden-xs hiddne-sm'),this.debug(127,0,3712));
    this._text_128 = this.renderer.createText(this._el_127,'Technical fee',this.debug(128,0,3744));
    this._el_129 = import4.createRenderElement(this.renderer,this._el_118,'th',new import4.InlineArray2(2,'class','hidden-xs hidden-sm'),this.debug(129,0,3762));
    this._text_130 = this.renderer.createText(this._el_129,'License fee',this.debug(130,0,3794));
    this._el_131 = import4.createRenderElement(this.renderer,this._el_118,'th',import4.EMPTY_INLINE_ARRAY,this.debug(131,0,3810));
    this._text_132 = this.renderer.createText(this._el_131,'Retail price',this.debug(132,0,3814));
    this._el_133 = import4.createRenderElement(this.renderer,this._el_116,'tbody',import4.EMPTY_INLINE_ARRAY,this.debug(133,0,3844));
    this._anchor_134 = this.renderer.createTemplateAnchor(this._el_133,this.debug(134,0,3851));
    this._vc_134 = new import16.ViewContainer(134,133,this,this._anchor_134);
    this._TemplateRef_134_5 = new import12.TemplateRef_(this,134,this._anchor_134);
    this._NgFor_134_6 = new import17.Wrapper_NgFor(this._vc_134.vcRef,this._TemplateRef_134_5,this.parentView.injectorGet(import21.IterableDiffers,this.parentIndex),this.ref);
    this._el_135 = import4.createRenderElement(this.renderer,this._el_102,'div',new import4.InlineArray2(2,'class','row'),this.debug(135,0,4189));
    this._el_136 = import4.createRenderElement(this.renderer,this._el_135,'div',new import4.InlineArray2(2,'class','col-md-12'),this.debug(136,0,4206));
    this._el_137 = import4.createRenderElement(this.renderer,this._el_136,'h3',import4.EMPTY_INLINE_ARRAY,this.debug(137,0,4229));
    this._text_138 = this.renderer.createText(this._el_137,'Asian',this.debug(138,0,4233));
    this._el_139 = import4.createRenderElement(this.renderer,this._el_136,'table',new import4.InlineArray2(2,'class','table table-striped'),this.debug(139,0,4243));
    this._el_140 = import4.createRenderElement(this.renderer,this._el_139,'thead',import4.EMPTY_INLINE_ARRAY,this.debug(140,0,4278));
    this._el_141 = import4.createRenderElement(this.renderer,this._el_140,'tr',import4.EMPTY_INLINE_ARRAY,this.debug(141,0,4285));
    this._el_142 = import4.createRenderElement(this.renderer,this._el_141,'th',import4.EMPTY_INLINE_ARRAY,this.debug(142,0,4289));
    this._text_143 = this.renderer.createText(this._el_142,'Name',this.debug(143,0,4293));
    this._el_144 = import4.createRenderElement(this.renderer,this._el_141,'th',import4.EMPTY_INLINE_ARRAY,this.debug(144,0,4302));
    this._text_145 = this.renderer.createText(this._el_144,'Core',this.debug(145,0,4306));
    this._el_146 = import4.createRenderElement(this.renderer,this._el_141,'th',import4.EMPTY_INLINE_ARRAY,this.debug(146,0,4315));
    this._text_147 = this.renderer.createText(this._el_146,'Memory',this.debug(147,0,4319));
    this._el_148 = import4.createRenderElement(this.renderer,this._el_141,'th',new import4.InlineArray2(2,'class','hidden-xs'),this.debug(148,0,4330));
    this._text_149 = this.renderer.createText(this._el_148,'Storage',this.debug(149,0,4352));
    this._el_150 = import4.createRenderElement(this.renderer,this._el_141,'th',new import4.InlineArray2(2,'class','hidden-xs hiddne-sm'),this.debug(150,0,4364));
    this._text_151 = this.renderer.createText(this._el_150,'Technical fee',this.debug(151,0,4396));
    this._el_152 = import4.createRenderElement(this.renderer,this._el_141,'th',new import4.InlineArray2(2,'class','hidden-xs hidden-sm'),this.debug(152,0,4414));
    this._text_153 = this.renderer.createText(this._el_152,'License fee',this.debug(153,0,4446));
    this._el_154 = import4.createRenderElement(this.renderer,this._el_141,'th',import4.EMPTY_INLINE_ARRAY,this.debug(154,0,4462));
    this._text_155 = this.renderer.createText(this._el_154,'Retail price',this.debug(155,0,4466));
    this._el_156 = import4.createRenderElement(this.renderer,this._el_139,'tbody',import4.EMPTY_INLINE_ARRAY,this.debug(156,0,4496));
    this._anchor_157 = this.renderer.createTemplateAnchor(this._el_156,this.debug(157,0,4503));
    this._vc_157 = new import16.ViewContainer(157,156,this,this._anchor_157);
    this._TemplateRef_157_5 = new import12.TemplateRef_(this,157,this._anchor_157);
    this._NgFor_157_6 = new import17.Wrapper_NgFor(this._vc_157.vcRef,this._TemplateRef_157_5,this.parentView.injectorGet(import21.IterableDiffers,this.parentIndex),this.ref);
    var disposable_0:Function = import4.subscribeToRenderElement(this,this._el_12,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_12));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._el_2,
      this._el_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._el_34,
      this._el_35,
      this._el_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._el_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._el_52,
      this._el_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._el_69,
      this._el_70,
      this._el_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._el_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._el_102,
      this._el_103,
      this._el_104,
      this._el_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._el_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._el_114,
      this._text_115,
      this._el_116,
      this._el_117,
      this._el_118,
      this._el_119,
      this._text_120,
      this._el_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._el_125,
      this._text_126,
      this._el_127,
      this._text_128,
      this._el_129,
      this._text_130,
      this._el_131,
      this._text_132,
      this._el_133,
      this._anchor_134,
      this._el_135,
      this._el_136,
      this._el_137,
      this._text_138,
      this._el_139,
      this._el_140,
      this._el_141,
      this._el_142,
      this._text_143,
      this._el_144,
      this._text_145,
      this._el_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._el_150,
      this._text_151,
      this._el_152,
      this._text_153,
      this._el_154,
      this._text_155,
      this._el_156,
      this._anchor_157
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_3.context; }
    if (((token === import11.RouterLinkWithHref) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkWithHref_12_3.context; }
    if (((token === import12.TemplateRef) && (134 === requestNodeIndex))) { return this._TemplateRef_134_5; }
    if (((token === import13.NgFor) && (134 === requestNodeIndex))) { return this._NgFor_134_6.context; }
    if (((token === import12.TemplateRef) && (157 === requestNodeIndex))) { return this._TemplateRef_157_5; }
    if (((token === import13.NgFor) && (157 === requestNodeIndex))) { return this._NgFor_157_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._HeaderComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(12,0,355);
    const currVal_12_0_0:any = this._arr_167('/getting-started');
    this._RouterLinkWithHref_12_3.check_routerLink(currVal_12_0_0,throwOnChange,false);
    this._RouterLinkWithHref_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    this.debug(134,0,3855);
    const currVal_134_0_0:any = this.context.pricingEurope;
    this._NgFor_134_6.check_ngForOf(currVal_134_0_0,throwOnChange,false);
    this._NgFor_134_6.ngDoCheck(this,this._anchor_134,throwOnChange);
    this.debug(157,0,4507);
    const currVal_157_0_0:any = this.context.pricingAsian;
    this._NgFor_157_6.check_ngForOf(currVal_157_0_0,throwOnChange,false);
    this._NgFor_157_6.ngDoCheck(this,this._anchor_157,throwOnChange);
    this._vc_134.detectChangesInNestedViews(throwOnChange);
    this._vc_157.detectChangesInNestedViews(throwOnChange);
    this._RouterLinkWithHref_12_3.checkHost(this,this,this._el_12,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_134.destroyNestedViews();
    this._vc_157.destroyNestedViews();
    this.compView_0.destroy();
    this.debug(0,0,0);
    this._RouterLinkWithHref_12_3.ngOnDestroy();
    this.debug(12,0,321);
    this.debug(134,0,3851);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 134)) { return new View_PricingComponent1(this.viewUtils,this,134,this._anchor_134,this._vc_134); }
    if ((nodeIndex == 157)) { return new View_PricingComponent2(this.viewUtils,this,157,this._anchor_157,this._vc_157); }
    return (null as any);
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.debug(12,0,321);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_12_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
const nodeDebugInfos_PricingComponent1:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class View_PricingComponent1 extends import1.DebugAppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_PricingComponent1,renderType_PricingComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_PricingComponent1,declaredViewContainer);
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'tr',import4.EMPTY_INLINE_ARRAY,this.debug(0,0,3851));
    this._el_1 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,this.debug(1,0,3890));
    this._text_2 = this.renderer.createText(this._el_1,'',this.debug(2,0,3894));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,this.debug(3,0,3912));
    this._text_4 = this.renderer.createText(this._el_3,'',this.debug(4,0,3916));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,this.debug(5,0,3934));
    this._text_6 = this.renderer.createText(this._el_5,'',this.debug(6,0,3938));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_0,'td',new import4.InlineArray2(2,'class','hidden-xs'),this.debug(7,0,3958));
    this._text_8 = this.renderer.createText(this._el_7,'',this.debug(8,0,3980));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_0,'td',new import4.InlineArray2(2,'class','hidden-xs hidden-sm'),this.debug(9,0,4001));
    this._text_10 = this.renderer.createText(this._el_9,'',this.debug(10,0,4033));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_0,'td',new import4.InlineArray2(2,'class','hidden-xs hidden-sm'),this.debug(11,0,4061));
    this._text_12 = this.renderer.createText(this._el_11,'',this.debug(12,0,4093));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,this.debug(13,0,4125));
    this._text_14 = this.renderer.createText(this._el_13,'',this.debug(14,0,4129));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(2,0,3894);
    const currVal_15:any = import4.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_2,currVal_15);
      this._expr_15 = currVal_15;
    }
    this.debug(4,0,3916);
    const currVal_16:any = import4.inlineInterpolate(1,'',this.context.$implicit.core,'');
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_4,currVal_16);
      this._expr_16 = currVal_16;
    }
    this.debug(6,0,3938);
    const currVal_17:any = import4.inlineInterpolate(1,'',this.context.$implicit.memory,'');
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_6,currVal_17);
      this._expr_17 = currVal_17;
    }
    this.debug(8,0,3980);
    const currVal_18:any = import4.inlineInterpolate(1,'',this.context.$implicit.storage,'');
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_8,currVal_18);
      this._expr_18 = currVal_18;
    }
    this.debug(10,0,4033);
    const currVal_19:any = import4.inlineInterpolate(1,'',this.context.$implicit.technicalFee,' €');
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_10,currVal_19);
      this._expr_19 = currVal_19;
    }
    this.debug(12,0,4093);
    const currVal_20:any = import4.inlineInterpolate(1,'',this.context.$implicit.slambyLicenseFee,' €');
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_12,currVal_20);
      this._expr_20 = currVal_20;
    }
    this.debug(14,0,4129);
    const currVal_21:any = import4.inlineInterpolate(1,'',this.context.$implicit.retailPrice,' €');
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_14,currVal_21);
      this._expr_21 = currVal_21;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
const nodeDebugInfos_PricingComponent2:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class View_PricingComponent2 extends import1.DebugAppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_PricingComponent2,renderType_PricingComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_PricingComponent2,declaredViewContainer);
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'tr',import4.EMPTY_INLINE_ARRAY,this.debug(0,0,4503));
    this._el_1 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,this.debug(1,0,4541));
    this._text_2 = this.renderer.createText(this._el_1,'',this.debug(2,0,4545));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,this.debug(3,0,4563));
    this._text_4 = this.renderer.createText(this._el_3,'',this.debug(4,0,4567));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,this.debug(5,0,4585));
    this._text_6 = this.renderer.createText(this._el_5,'',this.debug(6,0,4589));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_0,'td',new import4.InlineArray2(2,'class','hidden-xs'),this.debug(7,0,4609));
    this._text_8 = this.renderer.createText(this._el_7,'',this.debug(8,0,4631));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_0,'td',new import4.InlineArray2(2,'class','hidden-xs hidden-sm'),this.debug(9,0,4652));
    this._text_10 = this.renderer.createText(this._el_9,'',this.debug(10,0,4684));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_0,'td',new import4.InlineArray2(2,'class','hidden-xs hidden-sm'),this.debug(11,0,4712));
    this._text_12 = this.renderer.createText(this._el_11,'',this.debug(12,0,4744));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,this.debug(13,0,4776));
    this._text_14 = this.renderer.createText(this._el_13,'',this.debug(14,0,4780));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(2,0,4545);
    const currVal_15:any = import4.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_2,currVal_15);
      this._expr_15 = currVal_15;
    }
    this.debug(4,0,4567);
    const currVal_16:any = import4.inlineInterpolate(1,'',this.context.$implicit.core,'');
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_4,currVal_16);
      this._expr_16 = currVal_16;
    }
    this.debug(6,0,4589);
    const currVal_17:any = import4.inlineInterpolate(1,'',this.context.$implicit.memory,'');
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_6,currVal_17);
      this._expr_17 = currVal_17;
    }
    this.debug(8,0,4631);
    const currVal_18:any = import4.inlineInterpolate(1,'',this.context.$implicit.storage,'');
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_8,currVal_18);
      this._expr_18 = currVal_18;
    }
    this.debug(10,0,4684);
    const currVal_19:any = import4.inlineInterpolate(1,'',this.context.$implicit.technicalFee,' €');
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_10,currVal_19);
      this._expr_19 = currVal_19;
    }
    this.debug(12,0,4744);
    const currVal_20:any = import4.inlineInterpolate(1,'',this.context.$implicit.slambyLicenseFee,' €');
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_12,currVal_20);
      this._expr_20 = currVal_20;
    }
    this.debug(14,0,4780);
    const currVal_21:any = import4.inlineInterpolate(1,'',this.context.$implicit.retailPrice,' €');
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_14,currVal_21);
      this._expr_21 = currVal_21;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}