/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['html[_ngcontent-%COMP%], body[_ngcontent-%COMP%]{src:url("https://fonts.googleapis.com/css?family=Libre+Franklin:100,300,400,500");font-family:\'Libre Franklin\', sans-serif;height:100%;overflow:auto}h1[_ngcontent-%COMP%], h2[_ngcontent-%COMP%], h3[_ngcontent-%COMP%], h4[_ngcontent-%COMP%]{font-weight:300}p[_ngcontent-%COMP%]{font-weight:200}p.lead[_ngcontent-%COMP%]{font-weight:100}.table[_ngcontent-%COMP%]   thead[_ngcontent-%COMP%]   th[_ngcontent-%COMP%]{font-weight:400}.table[_ngcontent-%COMP%]   td[_ngcontent-%COMP%]{font-weight:300}@font-face{font-family:slamby-logo}.item[_ngcontent-%COMP%]{position:relative;float:left;width:100%;min-height:1px;padding-left:15px;padding-right:15px;position:relative;min-height:1px;padding-left:15px;padding-right:15px;position:relative;min-height:1px;padding-left:15px;padding-right:15px;padding:30px}@media (min-width: 768px){.item[_ngcontent-%COMP%]{float:left;width:50%}}@media (min-width: 992px){.item[_ngcontent-%COMP%]{float:left;width:25%}}'];