/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './footer.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './footer.component.css.shim';
import * as import10 from '@angular/router/src/directives/router_link';
import * as import11 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import12 from '@angular/router/src/router';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/common/src/location/location_strategy';
export class Wrapper_FooterComponent {
  /*private*/ _eventHandler:Function;
  context:import0.FooterComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.FooterComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const nodeDebugInfos_FooterComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.FooterComponent],import0.FooterComponent,{})];
var renderType_FooterComponent_Host:import3.RenderComponentType = import4.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_FooterComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.FooterComponent>;
  _FooterComponent_0_3:Wrapper_FooterComponent;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FooterComponent_Host0,renderType_FooterComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_FooterComponent_Host0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'pm-footer',import4.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_FooterComponent0(this.viewUtils,this,0,this._el_0);
    this._FooterComponent_0_3 = new Wrapper_FooterComponent();
    this.compView_0.create(this._FooterComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._FooterComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.FooterComponent) && (0 === requestNodeIndex))) { return this._FooterComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._FooterComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const FooterComponentNgFactory:import8.ComponentFactory<import0.FooterComponent> = new import8.ComponentFactory<import0.FooterComponent>('pm-footer',View_FooterComponent_Host0,import0.FooterComponent);
const styles_FooterComponent:any[] = [import9.styles];
const nodeDebugInfos_FooterComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import10.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import10.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import10.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_FooterComponent:import3.RenderComponentType = import4.createRenderComponentType('/home/peter/Desktop/git/angular2-aot-webpack/src/app/common/footer/footer.component.html',0,import5.ViewEncapsulation.Emulated,styles_FooterComponent,{});
export class View_FooterComponent0 extends import1.DebugAppView<import0.FooterComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _RouterLinkWithHref_20_3:import11.Wrapper_RouterLinkWithHref;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _RouterLinkWithHref_24_3:import11.Wrapper_RouterLinkWithHref;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _RouterLinkWithHref_28_3:import11.Wrapper_RouterLinkWithHref;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _arr_36:any;
  _arr_37:any;
  _arr_38:any;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FooterComponent0,renderType_FooterComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_FooterComponent0);
    this._arr_36 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_37 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_38 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',this.debug(1,0,23));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','footer'),this.debug(2,1,4));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',this.debug(3,1,24));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','message'),this.debug(4,2,8));
    this._text_5 = this.renderer.createText(this._el_4,'Slamby 2016',this.debug(5,2,29));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',this.debug(6,2,46));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_2,'ul',new import4.InlineArray2(2,'class','links'),this.debug(7,3,8));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',this.debug(8,3,26));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'li',import4.EMPTY_INLINE_ARRAY,this.debug(9,4,12));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_9,'a',new import4.InlineArray4(4,'href','https://github.com/slamby','target','_blank'),this.debug(10,4,16));
    this._text_11 = this.renderer.createText(this._el_10,'Github ',this.debug(11,4,68));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_10,'i',new import4.InlineArray4(4,'aria-hidden','true','class','fa fa-external-link sla-external-link'),this.debug(12,4,75));
    this._text_13 = this.renderer.createText(this._el_7,'\n            ',this.debug(13,4,156));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_7,'li',import4.EMPTY_INLINE_ARRAY,this.debug(14,5,12));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_14,'a',new import4.InlineArray4(4,'href','https://developers.slamby.com','target','_blank'),this.debug(15,5,16));
    this._text_16 = this.renderer.createText(this._el_15,'Slamby Developers ',this.debug(16,5,72));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_15,'i',new import4.InlineArray4(4,'aria-hidden','true','class','fa fa-external-link sla-external-link'),this.debug(17,5,90));
    this._text_18 = this.renderer.createText(this._el_7,'\n            ',this.debug(18,5,171));
    this._el_19 = import4.createRenderElement(this.renderer,this._el_7,'li',import4.EMPTY_INLINE_ARRAY,this.debug(19,6,12));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_19,'a',import4.EMPTY_INLINE_ARRAY,this.debug(20,6,16));
    this._RouterLinkWithHref_20_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import14.LocationStrategy,this.parentIndex));
    this._text_21 = this.renderer.createText(this._el_20,'Partners',this.debug(21,6,48));
    this._text_22 = this.renderer.createText(this._el_7,'\n            ',this.debug(22,6,65));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_7,'li',import4.EMPTY_INLINE_ARRAY,this.debug(23,7,12));
    this._el_24 = import4.createRenderElement(this.renderer,this._el_23,'a',import4.EMPTY_INLINE_ARRAY,this.debug(24,7,16));
    this._RouterLinkWithHref_24_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import14.LocationStrategy,this.parentIndex));
    this._text_25 = this.renderer.createText(this._el_24,'Company',this.debug(25,7,47));
    this._text_26 = this.renderer.createText(this._el_7,'\n            ',this.debug(26,7,63));
    this._el_27 = import4.createRenderElement(this.renderer,this._el_7,'li',import4.EMPTY_INLINE_ARRAY,this.debug(27,8,12));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_27,'a',import4.EMPTY_INLINE_ARRAY,this.debug(28,8,16));
    this._RouterLinkWithHref_28_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import14.LocationStrategy,this.parentIndex));
    this._text_29 = this.renderer.createText(this._el_28,'Legal',this.debug(29,8,60));
    this._text_30 = this.renderer.createText(this._el_7,'\n        ',this.debug(30,8,74));
    this._text_31 = this.renderer.createText(this._el_2,'\n    ',this.debug(31,9,13));
    this._text_32 = this.renderer.createText(this._el_0,'\n',this.debug(32,10,10));
    var disposable_0:Function = import4.subscribeToRenderElement(this,this._el_20,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_20));
    var disposable_1:Function = import4.subscribeToRenderElement(this,this._el_24,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_24));
    var disposable_2:Function = import4.subscribeToRenderElement(this,this._el_28,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_28));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.RouterLinkWithHref) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkWithHref_20_3.context; }
    if (((token === import10.RouterLinkWithHref) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._RouterLinkWithHref_24_3.context; }
    if (((token === import10.RouterLinkWithHref) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._RouterLinkWithHref_28_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(20,6,19);
    const currVal_20_0_0:any = this._arr_36('/partners');
    this._RouterLinkWithHref_20_3.check_routerLink(currVal_20_0_0,throwOnChange,false);
    this._RouterLinkWithHref_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    this.debug(24,7,19);
    const currVal_24_0_0:any = this._arr_37('/company');
    this._RouterLinkWithHref_24_3.check_routerLink(currVal_24_0_0,throwOnChange,false);
    this._RouterLinkWithHref_24_3.ngDoCheck(this,this._el_24,throwOnChange);
    this.debug(28,8,19);
    const currVal_28_0_0:any = this._arr_38('/legal/privacy-policy');
    this._RouterLinkWithHref_28_3.check_routerLink(currVal_28_0_0,throwOnChange,false);
    this._RouterLinkWithHref_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    this._RouterLinkWithHref_20_3.checkHost(this,this,this._el_20,throwOnChange);
    this._RouterLinkWithHref_24_3.checkHost(this,this,this._el_24,throwOnChange);
    this._RouterLinkWithHref_28_3.checkHost(this,this,this._el_28,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_20_3.ngOnDestroy();
    this.debug(20,6,16);
    this._RouterLinkWithHref_24_3.ngOnDestroy();
    this.debug(24,7,16);
    this._RouterLinkWithHref_28_3.ngOnDestroy();
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.debug(20,6,16);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_20_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.debug(24,7,16);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_24_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.debug(28,8,16);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_28_3.handleEvent(eventName,$event) && result);
    return result;
  }
}